Repository LabKey/platform, pull requests merged in 2019-11, with the labels that each got.

#284 37728: Insert/Update on Samples will clear out any existing data
  api/src/org/labkey/api/dataiterator/CoerceDataIterator.java
  api/src/org/labkey/api/query/AbstractQueryImportAction.java
  api/src/org/labkey/api/query/import.jsp
  experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
  experiment/src/org/labkey/experiment/samples/UploadSamplesHelper.java
Labels: issue verification complete, needs TeamCity test review

#577 Item 6451: ElisaAssayTest fix for assay designer sample domain set default value
  assay/src/org/labkey/assay/PlateBasedAssaySampleSetDomainKind.java
Labels: TeamCity test review complete

#581 Issue 38848: D3Renderer fix for legend text JS error
  internal/webapp/vis/src/internal/D3Renderer.js
Labels: needs TeamCity test review

#592 Item 6425: Changes to support user profile management within apps
  api/src/org/labkey/api/query/DefaultQueryUpdateService.java
  api/src/org/labkey/api/query/QueryForm.java
  api/src/org/labkey/api/query/QueryUpdateForm.java
  core/api-src/org/labkey/api/products/UserInfoMenuSection.java
  core/src/org/labkey/core/login/LoginController.java
  core/src/org/labkey/core/login/PasswordRule.java
  core/src/org/labkey/core/query/UsersTable.java
  core/src/org/labkey/core/user/UserController.java
Labels: TeamCity test review complete, issue verification complete

#639 UserTest fixes for user profile changes
  core/src/org/labkey/core/user/UserController.java
Labels: TeamCity test review complete

#642 Issue 39044: Fix for JS error when marking all notifications read on "View Notifications" page
  core/webapp/notification/Notification.js
  core/webapp/notification/NotificationViewAll.js
Labels: TeamCity test review complete

#643 Issue 38996: Fix project webpart outline around file icon when clicked/focus
  internal/webapp/extWidgets/IconPanel.css
Labels: TeamCity test review complete

#647 Item 6562: update module usages for @labkey/components
  assay/.npmrc
  assay/package-lock.json
  assay/package.json
  assay/src/client/AssayDataImport/AssayDataImport.tsx
  assay/src/client/AssayDesigner/AssayDesigner.tsx
  experiment/.npmrc
  experiment/package-lock.json
  experiment/package.json
  experiment/src/client/DomainDesigner/DomainDesigner.tsx
Labels: TeamCity test review complete
