Repository LabKey/platform, pull requests merged in 2019-04, with the labels that each got.

#24 Log threads at the time SQL deadlock exceptions to labkey.log
  api/src/org/labkey/api/util/ExceptionUtil.java
  core/src/org/labkey/core/admin/AdminController.java
Labels: code review complete

#21 Adding more timer output data and a titles.
  core/src/org/labkey/core/junit/JunitController.java
Labels: TeamCity test review complete, needs code review

#28 Fix to encode values in Ext detail fields and combos
  api/webapp/clientapi/ext4/Util.js
  internal/webapp/extWidgets/DetailsPanel.js
Labels: TeamCity test review complete

#38 [LabKey UX] Edit standard settings name/label/type - Domain API updates
  .gitignore
  api/gwtsrc/org/labkey/api/gwt/client/assay/model/GWTPropertyDescriptorMixin.java
  api/webapp/clientapi/core/Domain.js
  experiment/src/org/labkey/experiment/controllers/property/PropertyController.java
Labels: TeamCity test review complete

#60 Revert back to using compileInProductionMode setting from lib.xml when set
  api/src/org/labkey/api/view/template/LibClientDependency.java
Labels: TeamCity test review complete

#52 Item 5205: Configure QC metrics (#1)
  api/src/org/labkey/api/view/NavTreeCustomizer.java
  api/src/org/labkey/api/view/Portal.java
  api/webapp/clientapi/ext4/data/Store.js
Labels: needs TeamCity test review, needs issue verification

#53 File upload and data preview
  experiment/package-lock.json
  experiment/package.json
  experiment/src/client/AssayDesigner/AssayDesigner.tsx
  experiment/src/client/AssayDesigner/actions.ts
  experiment/src/client/DomainDesigner/DomainDesigner.tsx
  experiment/src/client/FileUploadPreview/FileUploadPreview.tsx
  experiment/src/client/FileUploadPreview/actions.ts
  experiment/src/client/FileUploadPreview/app.tsx
  experiment/src/client/FileUploadPreview/dev.tsx
  experiment/src/client/theme/Main.scss
  experiment/src/client/theme/style.js
  experiment/webpack/entryPoints.js
Labels: TeamCity test review complete, issue verification complete

#54 Item 5410: Basic Domain Designer
  api/gwtsrc/org/labkey/api/gwt/client/assay/model/GWTPropertyDescriptorMixin.java
  api/gwtsrc/org/labkey/api/gwt/client/ui/PropertiesEditor.java
  experiment/package-lock.json
  experiment/package.json
  experiment/src/client/DomainDesigner/DomainDesigner.tsx
  experiment/src/client/theme/domaindesigner.scss
  experiment/src/client/theme/style.js
  experiment/src/org/labkey/experiment/controllers/property/PropertyController.java
  internal/src/org/labkey/api/exp/property/DomainUtil.java
Labels: TeamCity test review complete, issue verification complete

#4 Item 5185: Zip Files for mass spec data
  api/src/org/labkey/api/files/DirectoryPattern.java
  api/src/org/labkey/api/files/FileContentService.java
  api/src/org/labkey/api/files/FilePattern.java
  filecontent/src/org/labkey/filecontent/FileContentController.java
  filecontent/src/org/labkey/filecontent/FileContentServiceImpl.java
  filecontent/webapp/File.lib.xml
  internal/webapp/internal-FileDrop.lib.xml
  internal/webapp/internal/FileDrop/FileDrop.js
  internal/webapp/internal/ZipLoad/ZipLoad.js
Labels: needs TeamCity test review, needs issue verification
