Repository LabKey/platform, pull requests merged in 2019-06, with the labels that each got.

#79 Item 5413: Domain Designer Add/Remove/Reorder Field
  experiment/package-lock.json
  experiment/package.json
  experiment/src/client/AssayDesigner/actions.ts
  experiment/src/client/AssayDesigner/models.ts
  experiment/src/client/DomainDesigner/DomainDesigner.tsx
  experiment/webpack/entryPoints.js
Labels: TeamCity test review complete, issue verification complete

#131 Use standard pattern for module containers
  build.gradle
  gradle.properties
Labels: needs TeamCity test review

#137 Issue 36813: update LABKEY.vis.Plot JS documentation for plot params
  internal/webapp/vis/src/plot.js
Labels: TeamCity test review complete

#140 Issue 36443: Show visit sequence num when visit range appears split in participant view
  study/src/org/labkey/study/view/participantAll.jsp
Labels: TeamCity test review complete

#156 NPM package updates
  core/package-lock.json
  core/package.json
  experiment/package-lock.json
  experiment/package.json
Labels: TeamCity test review complete

#161 Issue 36980: Assay getProtocol getting NPE if assay definition not found
  study/src/org/labkey/study/assay/AssayServiceImpl.java
  study/src/org/labkey/study/controllers/assay/actions/GetProtocolAction.java
Labels: TeamCity test review complete

#151 Issue 37592: Add search document for SampleSets
  experiment/resources/schemas/dbscripts/postgresql/exp-19.11-19.12.sql
  experiment/resources/schemas/dbscripts/sqlserver/exp-19.11-19.12.sql
  experiment/resources/schemas/exp.xml
  experiment/src/org/labkey/experiment/ExperimentModule.java
  experiment/src/org/labkey/experiment/api/ExpSampleSetImpl.java
  experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
  experiment/src/org/labkey/experiment/api/SampleSetServiceImpl.java
  experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
Labels: TeamCity test review complete, needs issue verification

#177 'ColumnInfo is locked' related test failure fix (for TargetStudyTest.runUITests).
  api/src/org/labkey/api/study/actions/StudyPickerColumn.java
Labels: TeamCity test review complete, code review complete

#174 Issue 37324: Skip processing if a data file is missing during list archive import
  list/src/org/labkey/list/model/ListImporter.java
Labels: TeamCity test review complete, code review complete

#193 Issue 36854: Remove json converting functions from Experiment module
  api/src/org/labkey/api/exp/api/ExperimentService.java
  experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
Labels: TeamCity test review complete

#170 Issue 37582: Deleting sample deletes derivation run as well, removing lineage from “sister” samples
  api/src/org/labkey/api/exp/api/ExperimentService.java
  experiment/src/org/labkey/experiment/ParentChildView.java
  experiment/src/org/labkey/experiment/api/ExpMaterialImpl.java
  experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
  experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
Labels: needs TeamCity test review, needs issue verification

#136 Item 5698 Add/remove fields - API dev
  api/gwtsrc/org/labkey/api/gwt/client/model/GWTPropertyDescriptor.java
  api/src/org/labkey/api/action/ApiResponseWriter.java
  api/src/org/labkey/api/audit/query/AbstractAuditDomainKind.java
  api/src/org/labkey/api/exp/OntologyManager.java
  api/src/org/labkey/api/exp/property/DomainKind.java
  api/src/org/labkey/api/exp/property/TestDomainKind.java
  api/src/org/labkey/api/query/PropertyValidationError.java
  api/src/org/labkey/api/query/SimpleValidationError.java
  api/src/org/labkey/api/query/ValidationError.java
  api/src/org/labkey/api/query/ValidationException.java
  experiment/src/org/labkey/experiment/api/property/DomainPropertyImpl.java
  experiment/src/org/labkey/experiment/controllers/property/PropertyController.java
  internal/src/org/labkey/api/exp/property/AbstractDomainKind.java
  internal/src/org/labkey/api/exp/property/DomainEditorServiceBase.java
  internal/src/org/labkey/api/exp/property/DomainTemplate.java
  internal/src/org/labkey/api/exp/property/DomainUtil.java
  internal/src/org/labkey/api/query/ExtendedTableDomainKind.java
  study/test/src/org/labkey/test/tests/study/StudyDatasetDomainTest.java
Labels: TeamCity test review complete, code review complete, issue verification complete

#183 Issue 31857: Chart wizard option for custom margin sizes
  visualization/resources/web/vis/chartWizard/chartLayoutDialog/genericChartOptionsPanel.js
  visualization/resources/web/vis/chartWizard/genericChartPanel.js
  visualization/resources/web/vis/genericChart/genericChartHelper.js
Labels: TeamCity test review complete

#163 Item 5836: UX Assay Data Import - initial end-to-end for run import and assay creation from file
  api/webapp/clientapi/core/Query.js
  api/webapp/clientapi/dom/Query.js
  experiment/package-lock.json
  experiment/package.json
  experiment/src/client/AssayDataImport/AssayDataImport.tsx
  experiment/src/client/AssayDataImport/AssayDesignForm.tsx
  experiment/src/client/AssayDataImport/AssayRunForm.tsx
  experiment/src/client/AssayDataImport/app.tsx
  experiment/src/client/AssayDataImport/constants.ts
  experiment/src/client/AssayDataImport/dev.tsx
  experiment/src/client/AssayDesigner/AssayDesigner.tsx
  experiment/src/client/AssayDesigner/actions.ts
  experiment/src/client/AssayDesigner/models.ts
  experiment/src/client/FileUploadPreview/FileUploadPreview.tsx
  experiment/src/client/FileUploadPreview/actions.ts
  experiment/src/client/theme/assaydataimport.scss
  experiment/src/client/theme/style.js
  experiment/src/client/typings/main.d.ts
  experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
  experiment/src/org/labkey/experiment/controllers/property/PropertyController.java
  experiment/src/org/labkey/experiment/createSampleSet.jsp
  experiment/webpack/entryPoints.js
  study/src/org/labkey/study/controllers/assay/actions/SaveProtocolAction.java
Labels: TeamCity test review complete, issue verification complete

#203 Issue 37763: Cursor placement issue when initially editing existing query via Schema Browser
  query/webapp/query/QueryEditorPanel.js
Labels: TeamCity test review complete

#202 Refactored Lock property from having true/false to have an enum to support partial lock case.
  api/gwtsrc/org/labkey/api/gwt/client/LockedPropertyType.java
  api/gwtsrc/org/labkey/api/gwt/client/model/GWTPropertyDescriptor.java
  internal/src/org/labkey/api/exp/property/DomainUtil.java
  study/test/src/org/labkey/test/tests/study/StudyDatasetDomainTest.java
Labels: TeamCity test review complete, code review complete

#205 Item 5836: UX Assay Data Import - add experimental feature flag to add button to Assay List query view
  list/src/org/labkey/list/model/ListManagerSchema.java
  study/src/org/labkey/study/StudyModule.java
  study/src/org/labkey/study/assay/AssayManager.java
  study/src/org/labkey/study/assay/query/AssayListPortalView.java
  study/src/org/labkey/study/assay/query/AssayListQueryView.java
  study/src/org/labkey/study/query/LocationQueryView.java
  study/src/org/labkey/study/view/assayList2.jsp
Labels: TeamCity test review complete

#212 Issue 37561: during XAR import, don't try to load/hash from an existing exp.Data dataFileUrl if that file doesn't exist
  experiment/src/org/labkey/experiment/XarReader.java
Labels: TeamCity test review complete
