Repository LabKey/platform, pull requests merged in 2019-07, with the labels that each got.

#222 37756: Junit page no longer respects suite (DRT, BVT)
  core/src/org/labkey/core/junit/JunitController.java
Labels: TeamCity test review complete, code review complete, needs issue verification

#214 Item 5900: Sample Set CRUD API updates for sample set create/update/delete
  api/src/org/labkey/api/exp/query/ExpSampleSetTable.java
  api/src/org/labkey/api/security/permissions/DesignSampleSetPermission.java
  api/src/org/labkey/api/security/roles/EditorRole.java
  experiment/src/org/labkey/experiment/SampleSetWebPart.java
  experiment/src/org/labkey/experiment/api/ExpSampleSetTableImpl.java
  experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
  internal/src/org/labkey/experiment/api/SampleSetDomainKind.java
Labels: TeamCity test review complete, issue verification complete

#239 Issue 37219: Sample set Parent column
  experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
  experiment/src/org/labkey/experiment/createSampleSet.jsp
Labels: TeamCity test review complete, issue verification complete

#251 Issue 37946: Alias column conflict with import alias
  api/src/org/labkey/api/dataiterator/SimpleTranslator.java
  experiment/src/org/labkey/experiment/ExpDataIterators.java
  experiment/src/org/labkey/experiment/api/ExpSampleSetImpl.java
Labels: issue verification complete

#258 UX Domain Designer experimental feature flag
  api/src/org/labkey/api/exp/api/ExperimentService.java
  api/src/org/labkey/api/exp/api/ExperimentUrls.java
  core/src/org/labkey/core/query/UsersDomainKind.java
  experiment/src/client/DomainDesigner/DomainDesigner.tsx
  experiment/src/org/labkey/experiment/ExperimentModule.java
  experiment/src/org/labkey/experiment/api/DataClassDomainKind.java
  experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
  experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
  internal/src/org/labkey/api/query/SimpleTableDomainKind.java
  internal/src/org/labkey/experiment/api/SampleSetDomainKind.java
  study/src/org/labkey/study/controllers/StudyDefinitionController.java
  study/src/org/labkey/study/query/studydesign/AbstractStudyDesignDomainKind.java
Labels: TeamCity test review complete

#262 UX Domain Designer: update packages in experiment package.json
  experiment/package-lock.json
  experiment/package.json
Labels: TeamCity test review complete

#257 Item 5973, 6024, and 6034: Assay data create and delete
  api/src/org/labkey/api/study/assay/BatchListQueryView.java
  experiment/package-lock.json
  experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
  internal/src/org/labkey/experiment/api/SampleSetDomainKind.java
Labels: TeamCity test review complete, issue verification complete

#234 Lookup Field Support in Domain Designer
  api/webapp/clientapi/core/Query.js
  core/src/org/labkey/core/query/UsersDomainKind.java
  experiment/package-lock.json
  experiment/package.json
  experiment/src/client/DomainDesigner/DomainDesigner.tsx
  internal/src/org/labkey/api/query/SimpleTableDomainKind.java
  query/src/org/labkey/query/controllers/QueryController.java
  study/src/org/labkey/study/controllers/StudyDefinitionController.java
  study/src/org/labkey/study/query/studydesign/AbstractStudyDesignDomainKind.java
Labels: TeamCity test review complete, issue verification complete
