Repository LabKey/platform, pull requests merged in 2019-12, with the labels that each got.

#654 Item 6508: Permissions page change to use LABKEY.Security.getPolicy instead of duplicate it
  api/webapp/clientapi/core/Security.js
  assay/package-lock.json
  assay/package.json
  core/api-src/org/labkey/api/products/ProductMenuProvider.java
  core/api-src/org/labkey/api/products/UserInfoMenuSection.java
  core/src/org/labkey/core/security/SecurityApiActions.java
  core/webapp/Security/util/Policy.js
  experiment/package-lock.json
  experiment/package.json
  experiment/src/org/labkey/experiment/api/SampleSetUpdateServiceDI.java
Labels: TeamCity test review complete

#667 Update to @labkey/components version which has dependencies that replace @labkey/dependencies
  assay/package-lock.json
  assay/package.json
  experiment/package-lock.json
  experiment/package.json
Labels: TeamCity test review complete

#671 Item 5511: Changes to better support login and password actions for SM app
  api/src/org/labkey/api/security/AuthenticationManager.java
  api/src/org/labkey/api/settings/LookAndFeelPropertiesManager.java
  api/src/org/labkey/api/util/PageFlowUtil.java
  api/src/org/labkey/api/view/template/PageConfig.java
  assay/package-lock.json
  assay/package.json
  core/resources/themes/sky/_variables.scss
  core/resources/views/login.html
  core/resources/views/register.html
  core/src/org/labkey/core/CoreModule.java
  core/src/org/labkey/core/admin/AdminController.java
  core/src/org/labkey/core/admin/lookAndFeelProperties.jsp
  core/src/org/labkey/core/login/LoginController.java
  core/src/org/labkey/core/login/finishResetPassword.jsp
  core/src/org/labkey/core/login/resetPassword.jsp
  core/src/org/labkey/core/login/setPassword.jsp
  core/src/org/labkey/core/security/SecurityApiActions.java
  core/src/org/labkey/core/view/template/bootstrap/header.jsp
  core/webapp/login.css
  core/webapp/register.js
  devtools/src/org/labkey/devtools/authentication/TestSecondaryController.java
  experiment/package-lock.json
  experiment/package.json
  wiki/src/org/labkey/wiki/WikiModule.java
Labels: TeamCity test review complete

#533 Issue 38449: Preserve last modified time when uploading single file
  core/src/org/labkey/core/webdav/DavController.java
  filecontent/webapp/File/panel/Upload.js
Labels: code review complete, issue verification complete

#547 Issue 38643: S3-backed FWP reports no files when it can't communicate with S3
  core/src/org/labkey/core/webdav/DavController.java
  filecontent/webapp/File/system/Webdav.js
Labels: code review complete, issue verification complete

#684 SM Type keyword nets 0 results, should include Sample Types
  experiment/src/org/labkey/experiment/api/ExpSampleSetImpl.java
Labels: needs issue verification

#691 Misc domain designer fixes for Sample Manager
  assay/package-lock.json
  assay/package.json
  experiment/package-lock.json
  experiment/package.json
  experiment/src/client/DomainDesigner/DomainDesigner.tsx
  experiment/src/client/DomainDesigner/domainDesigner.scss
Labels: TeamCity test review complete

#686 Item 6392: Split WebSocket JS configuration out from experimental Notification.js
  .gitattributes
  api/src/org/labkey/api/util/ErrorView.java
  api/src/org/labkey/api/view/UnauthorizedException.java
  api/webapp/clientapi.lib.xml
  api/webapp/clientapi/core/Utils.js
  api/webapp/clientapi/dom/Utils.js
  api/webapp/clientapi/dom/WebSocket.js
  core/webapp/login.js
  core/webapp/notification/Notification.js
Labels: TeamCity test review complete, code review complete

#710 WebSocket fix for issue with Firefox sending unexpected event code on page reload
  api/webapp/clientapi/dom/WebSocket.js
Labels: TeamCity test review complete
