Repository LabKey/platform, pull requests merged in 2019-09, with the labels that each got.

#370 Issue 38298: Errors when indexing .7z files in search
  api/build.gradle
  search/src/org/labkey/search/model/LuceneSearchServiceImpl.java
Labels: code review complete, needs TeamCity test review

#384 Issue 38403: Support DB report name as URL parameter in addition to RowId
  api/src/org/labkey/api/query/QuerySettings.java
  api/src/org/labkey/api/reports/ReportService.java
  api/src/org/labkey/api/reports/report/AbstractReportIdentifier.java
  api/src/org/labkey/api/reports/report/DbReportIdentifier.java
  api/src/org/labkey/api/reports/report/RReport.java
  api/src/org/labkey/api/reports/report/ReportDescriptor.java
  api/src/org/labkey/api/reports/report/ReportIdentifierConverter.java
  api/src/org/labkey/api/reports/report/view/ReportUtil.java
  query/src/org/labkey/query/reports/ReportServiceImpl.java
  query/src/org/labkey/query/reports/ReportsController.java
  query/src/org/labkey/query/reports/ReportsWebPartFactory.java
  study/src/org/labkey/study/controllers/StudyController.java
  study/src/org/labkey/study/controllers/reports/ReportsController.java
  study/src/org/labkey/study/view/participantAll.jsp
  study/src/org/labkey/study/view/viewPreferences.jsp
  visualization/src/org/labkey/visualization/VisualizationController.java
Labels: needs TeamCity test review

#348 Issue 38446: Add viewName to BrowseDataTree API response
  api/src/org/labkey/api/data/views/DataViewInfo.java
  api/src/org/labkey/api/data/views/DataViewService.java
  api/src/org/labkey/api/data/views/DefaultViewInfo.java
  internal/webapp/_images/bar_chart.svg
  internal/webapp/_images/box_plot.svg
  internal/webapp/_images/custom_grid.svg
  internal/webapp/_images/pie_chart.svg
  internal/webapp/_images/sample_comparison.svg
  internal/webapp/_images/xy_line.svg
  internal/webapp/_images/xy_scatter.svg
  query/src/org/labkey/query/view/AbstractQueryDataViewProvider.java
  study/src/org/labkey/study/reports/ReportViewProvider.java
Labels: needs TeamCity test review

#402 Epic 6147: Domain designer prioritized updates
  .gitignore
  api/src/org/labkey/api/exp/property/DomainKind.java
  assay/api-src/org/labkey/api/assay/AssayDomainKind.java
  assay/package-lock.json
  assay/package.json
  core/src/org/labkey/core/query/UsersDomainKind.java
  experiment/package-lock.json
  experiment/package.json
  experiment/src/client/DomainDesigner/DomainDesigner.tsx
  experiment/src/org/labkey/experiment/api/DataClassDomainKind.java
  experiment/src/org/labkey/experiment/controllers/property/GWTDomainMixin.java
  internal/src/org/labkey/api/exp/property/AbstractDomainKind.java
  internal/src/org/labkey/api/exp/property/DomainUtil.java
  internal/src/org/labkey/api/query/SimpleTableDomainKind.java
  internal/src/org/labkey/experiment/api/SampleSetDomainKind.java
  study/src/org/labkey/study/model/DatasetDomainKind.java
  study/src/org/labkey/study/query/studydesign/AbstractStudyDesignDomainKind.java
Labels: needs TeamCity test review, needs issue verification

#369 Item #5692: Add import parent alias components for SampleSets
  assay/package-lock.json
  assay/package.json
  experiment/package-lock.json
  experiment/package.json
  experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
  experiment/src/org/labkey/experiment/createSampleSet.jsp
Labels: code review complete, needs TeamCity test review

#417 Issue 38484: Sample set update page help link encoding
  api/src/org/labkey/api/jsp/taglib/InputTag.java
  experiment/src/org/labkey/experiment/createSampleSet.jsp
Labels: code review complete, issue verification complete, needs TeamCity test review

#432 19.2 fb 38311 38448 automation
  study/test/sampledata/assay/GPAT_Run1.tsv
  study/test/sampledata/assay/Parent_Assay_38448.tsv
  study/test/sampledata/assay/Parent_Assay_38448.xar.xml
  study/test/sampledata/assay/Parent_Assay_38448_Reimport.tsv
  study/test/sampledata/assay/Simple_GPAT.xar.xml
  study/test/sampledata/assay/Subfolder_A_Assay_38448.tsv
  study/test/sampledata/assay/Subfolder_A_Assay_38448.xar.xml
  study/test/sampledata/assay/Subfolder_A_Assay_38448_Reimport.tsv
  study/test/src/org/labkey/test/tests/experiment/ExpSchemaPropagateFilterTest.java
  study/test/src/org/labkey/test/tests/study/QuerySnapshotTest.java
Labels: TeamCity test review complete, issue verification complete

#448 Issue 38127: Update to latest glass release versions
  assay/package-lock.json
  assay/package.json
  experiment/package-lock.json
  experiment/package.json
Labels: TeamCity test review complete

#452 Issue 38541: Integer-type or study participant lookups as fields in File Properties don't display the title
  filecontent/src/org/labkey/filecontent/FileContentController.java
Labels: TeamCity test review complete, code review complete, issue verification complete

#478 Issue 32693: default text-link to have pointer cursor
  core/resources/styles/scss/labkey/_labkey.scss
Labels: TeamCity test review complete

#479 Issue 38502: use container.equals() check for getDomain()
  experiment/src/org/labkey/experiment/controllers/property/PropertyController.java
Labels: TeamCity test review complete
