Repository LabKey/platform, pull requests merged in 2019-08, with the labels that each got.

#304 Item 6116: assay design deletion
  experiment/package-lock.json
  experiment/package.json
  experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
Labels: TeamCity test review complete, issue verification complete

#352 Issue 38333: Cell background conditional formatting ignored upon row hover or click
  api/src/org/labkey/api/data/ConditionalFormat.java
Labels: TeamCity test review complete

#372 Issue 38386: Tika cant find parser class for HDF files
  search/src/org/labkey/search/model/tikaConfig.xml
Labels: needs TeamCity test review, needs code review, needs issue verification
