Repository LabKey/platform, pull requests merged in 2019-10, with the labels that each got.

#462 Issue 38508: Check location of file for preview
  experiment/src/org/labkey/experiment/controllers/property/PropertyController.java
Labels: TeamCity test review complete, issue verification complete

#486 Issue 37736: Fix for wizard template page to show step text and mark active
  core/src/org/labkey/core/view/template/bootstrap/wizard.jsp
Labels: TeamCity test review complete

#499 Issue 38628: update chart display text for missing measure name to use name instead of label
  visualization/resources/web/vis/chartWizard/genericChartPanel.js
  visualization/resources/web/vis/genericChart/genericChartHelper.js
Labels: TeamCity test review complete

#509 Issue 34703: Linked Schema override/revert links - remove inline style for font-size
  query/src/org/labkey/query/view/linkedSchema.jsp
Labels: TeamCity test review complete

#513 Issue 38007: show notification count on page load but only Ajax panel contents on first panel open
  api/src/org/labkey/api/notification/notificationpanel.jsp
  api/src/org/labkey/api/util/PageFlowUtil.java
  core/webapp/notification/Notification.js
Labels: TeamCity test review complete

#491 Update core/build.js for using @labkey/api
  core/build.js
  core/package-lock.json
  core/package.json
Labels: code review complete, issue verification complete

#492 Item 6199: support other assay provider types in AssayDesignerPanels and AssayPropertiesPanel
  api/gwtsrc/org/labkey/api/gwt/client/assay/AssayDesignerMainPanel.java
  api/gwtsrc/org/labkey/api/gwt/client/assay/model/GWTProtocol.java
  api/gwtsrc/org/labkey/api/gwt/client/model/GWTContainer.java
  api/src/org/labkey/api/assay/AbstractAssayProvider.java
  api/src/org/labkey/api/assay/actions/DesignerAction.java
  assay/api-src/org/labkey/api/assay/plate/AbstractPlateBasedAssayProvider.java
  assay/package-lock.json
  assay/package.json
  assay/src/client/AssayDataImport/AssayDataImport.tsx
  assay/src/client/AssayDesigner/AssayDesigner.tsx
  assay/src/org/labkey/assay/AssayController.java
  assay/src/org/labkey/assay/AssayServiceImpl.java
  assay/src/org/labkey/assay/TsvAssayProvider.java
  assay/src/org/labkey/assay/actions/GetProtocolAction.java
  experiment/package-lock.json
  experiment/package.json
  experiment/src/client/DomainDesigner/DomainDesigner.tsx
  study/test/src/org/labkey/test/tests/experiment/ExperimentAPITest.java
  study/test/src/org/labkey/test/tests/study/AssayTest.java
  study/test/src/org/labkey/test/tests/study/CopyAssayToStudyTest.java
Labels: TeamCity test review complete, issue verification complete

#538 Move DesignSampleSetPermission from EditorRole to FolderAdminRole
  api/src/org/labkey/api/security/roles/EditorRole.java
  api/src/org/labkey/api/security/roles/FolderAdminRole.java
Labels: needs TeamCity test review

#532 Issue 37799: Bulk edit button on list doesn't accurately reflect selected row count
  api/src/org/labkey/api/data/DataRegion.java
Labels: needs issue verification

#549 Fix for NPE in GetValidPublishTargetsAction when study module does not exist
  assay/src/org/labkey/assay/AssayController.java
Labels: TeamCity test review complete

#515 Item 5917: Domain Designer validators, conditional formatting and default values
  api/src/org/labkey/api/exp/property/DomainKind.java
  assay/api-src/org/labkey/api/assay/AssayDomainKind.java
  assay/package-lock.json
  assay/package.json
  assay/src/client/AssayDesigner/app.tsx
  assay/src/client/AssayDesigner/dev.tsx
  assay/src/org/labkey/assay/AssayServiceImpl.java
  assay/webpack/dev.config.js
  experiment/package-lock.json
  experiment/package.json
  experiment/src/client/DomainDesigner/app.tsx
  experiment/src/client/DomainDesigner/dev.tsx
  experiment/src/org/labkey/experiment/controllers/property/GWTDomainMixin.java
  experiment/src/org/labkey/experiment/controllers/property/PropertyController.java
  experiment/webpack/dev.config.js
  filecontent/src/org/labkey/filecontent/FilePropertiesDomainKind.java
  filecontent/src/org/labkey/filecontent/FilePropertiesServiceImpl.java
  internal/src/org/labkey/api/exp/property/DomainEditorServiceBase.java
  internal/src/org/labkey/api/exp/property/DomainUtil.java
  issues/src/org/labkey/issue/actions/IssueServiceAction.java
  issues/src/org/labkey/issue/query/IssueDefDomainKind.java
  list/src/org/labkey/list/model/ListEditorServiceImpl.java
  study/src/org/labkey/study/controllers/DatasetServiceImpl.java
Labels: needs TeamCity test review

#548 Issue 38735: SND pipeline import failing on container conversion to uniqueidentifier
  api/src/org/labkey/api/query/DefaultQueryUpdateService.java
Labels: TeamCity test review complete

#543 Item 6120: support for domain designer with addition of Sample lookup data type
  assay/package-lock.json
  assay/package.json
  experiment/package-lock.json
  experiment/package.json
Labels: TeamCity test review complete, issue verification complete

#559 Fb ux assay test migrate
  assay/webpack/entryPoints.js
  experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
  experiment/src/org/labkey/experiment/controllers/property/PropertyController.java
  experiment/webpack/entryPoints.js
  internal/src/org/labkey/api/issues/AbstractIssuesListDefDomainKind.java
  query/src/org/labkey/query/controllers/GetQueryDetailsAction.java
  study/src/org/labkey/study/controllers/StudyDefinitionController.java
  study/src/org/labkey/study/model/StudyDomainKind.java
  study/src/org/labkey/study/query/studydesign/AbstractStudyDesignDomainKind.java
  study/test/src/org/labkey/test/tests/experiment/ExperimentAPITest.java
  study/test/src/org/labkey/test/tests/study/AssayTest.java
  study/test/src/org/labkey/test/tests/study/StudySimpleExportTest.java
Labels: TeamCity test review complete

#563 Item 6474: Enable new assay designer and single domain designer by default
  .gitattributes
  api/gwtsrc/org/labkey/api/gwt/client/assay/AssayDesignerMainPanel.java
  api/src/org/labkey/api/assay/AssayService.java
  api/src/org/labkey/api/assay/actions/DesignerAction.java
  assay/gwtsrc/gwt/client/org/labkey/assay/AssayApplication.java
  assay/gwtsrc/gwt/client/org/labkey/assay/designer/client/AssayDesigner.java
  assay/src/org/labkey/assay/AssayManager.java
  experiment/gwtsrc/org/labkey/experiment/property/Designer.gwt.xml
  experiment/gwtsrc/org/labkey/experiment/property/client/Designer.java
  experiment/gwtsrc/org/labkey/experiment/property/client/PropertyService.java
  experiment/gwtsrc/org/labkey/experiment/property/client/PropertyServiceAsync.java
  experiment/src/org/labkey/experiment/ExperimentModule.java
  experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
  experiment/src/org/labkey/experiment/controllers/property/PropertyController.java
  study/gwtsrc/gwt/client/org/labkey/specimen/client/SpecimenDesigner.java
  study/test/src/org/labkey/test/tests/study/StudySimpleExportTest.java
Labels: TeamCity test review complete

#570 Item 6451: Assay and domain designer misc polish updates and bug fixes
  api/gwtsrc/org/labkey/api/gwt/client/model/GWTDomain.java
  api/src/org/labkey/api/assay/AbstractAssayProvider.java
  api/src/org/labkey/api/exp/api/ExperimentUrls.java
  api/src/org/labkey/api/exp/property/DomainKind.java
  assay/api-src/org/labkey/api/assay/AssayDomainKind.java
  assay/package-lock.json
  assay/package.json
  assay/src/org/labkey/assay/AssayServiceImpl.java
  core/src/org/labkey/core/query/UsersDomainKind.java
  experiment/package-lock.json
  experiment/package.json
  experiment/src/client/DomainDesigner/DomainDesigner.tsx
  experiment/src/org/labkey/experiment/api/DataClassDomainKind.java
  experiment/src/org/labkey/experiment/api/VocabularyDomainKind.java
  experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
  experiment/src/org/labkey/experiment/controllers/property/DomainForm.java
  experiment/src/org/labkey/experiment/controllers/property/PropertyController.java
  experiment/webpack/entryPoints.js
  internal/src/org/labkey/api/exp/property/AbstractDomainKind.java
  internal/src/org/labkey/api/exp/property/DomainUtil.java
  internal/src/org/labkey/api/issues/AbstractIssuesListDefDomainKind.java
  internal/src/org/labkey/api/query/SimpleTableDomainKind.java
  internal/src/org/labkey/experiment/api/SampleSetDomainKind.java
  list/src/org/labkey/list/model/ListDomainKind.java
  study/src/org/labkey/study/controllers/StudyDefinitionController.java
  study/src/org/labkey/study/model/DatasetDomainKind.java
  study/src/org/labkey/study/model/StudyDomainKind.java
  study/src/org/labkey/study/query/studydesign/AbstractStudyDesignDomainKind.java
  study/test/src/org/labkey/test/tests/study/AssayTest.java
  study/test/src/org/labkey/test/tests/study/StudySimpleExportTest.java
  survey/src/org/labkey/survey/query/SurveyTableDomainKind.java
Labels: TeamCity test review complete, issue verification complete
