Repository LabKey/platform, pull requests merged in 2020-05, with the labels that each got.

#1114 Update to latest @labkey/components package with DataClassModel converted to immer
  assay/package-lock.json
  assay/package.json
  core/package-lock.json
  core/package.json
  experiment/package-lock.json
  experiment/package.json
  list/package-lock.json
  list/package.json
  query/package-lock.json
  query/package.json
  study/package-lock.json
  study/package.json
Labels: TeamCity test review complete

#1120 Domain designer cleanup for consistent use of dirty state check with BeforeUnload
  api/gwtsrc/org/labkey/api/gwt/client/model/GWTPropertyDescriptor.java
  assay/src/client/AssayDesigner/AssayDesigner.tsx
  experiment/src/client/DataClassDesigner/DataClassDesigner.tsx
  experiment/src/client/DomainDesigner/DomainDesigner.tsx
  experiment/src/client/SampleTypeDesigner/SampleTypeDesigner.tsx
  list/src/client/Designer/Designer.tsx
  list/src/org/labkey/list/controllers/ListController.java
  list/src/org/labkey/list/model/ListDomainKindProperties.java
  list/src/org/labkey/list/view/ListImportServiceImpl.java
  query/src/client/QueryMetadataEditor/QueryMetadataEditor.tsx
  study/src/client/DatasetDesigner/DatasetDesigner.tsx
Labels: TeamCity test review complete

#1134 40226: Respect "skipPrefixes" in async region
  api/webapp/clientapi/dom/DataRegion.js
  query/resources/views/QWPDemo.html
  query/webapp/QWPDemo.js
Labels: needs TeamCity test review

#1141 Change domain form display options
  assay/package-lock.json
  assay/package.json
  core/package-lock.json
  core/package.json
  experiment/package-lock.json
  experiment/package.json
  list/package-lock.json
  list/package.json
  query/package-lock.json
  query/package.json
  query/src/client/QueryMetadataEditor/QueryMetadataEditor.tsx
  query/src/org/labkey/query/MetadataTableJSON.java
  query/src/org/labkey/query/controllers/QueryController.java
  query/src/org/labkey/query/model/MetadataTableJSONMixin.java
  study/package-lock.json
  study/package.json
Labels: TeamCity test review complete, issue verification complete

#1146 RlabkeyTest fixes related to labkey.domain.create changes with study datasets
  internal/src/org/labkey/api/issues/AbstractIssuesListDefDomainKind.java
  internal/src/org/labkey/api/issues/IssuesListDefService.java
  issues/src/org/labkey/issue/model/IssuesListDefServiceImpl.java
  study/src/org/labkey/study/model/DatasetDomainKind.java
  study/src/org/labkey/study/model/DatasetDomainKindProperties.java
Labels: TeamCity test review complete

#1165 Use $.each() instead of Array.forEach()
  api/webapp/clientapi/dom/DataRegion.js
Labels: needs TeamCity test review

#1160 Admin console defaults to "Settings"
  api/src/org/labkey/api/view/menu/SiteAdminMenu.java
  core/src/org/labkey/core/admin/admin.jsp
  mothership/test/src/org/labkey/test/util/mothership/MothershipHelper.java
Labels: needs TeamCity test review

#1179 Item 7326: Study query snapshot conversion to new dataset designer
  study/src/org/labkey/study/controllers/StudyController.java
  study/src/org/labkey/study/view/createDatasetSnapshot.jsp
  study/src/org/labkey/study/view/editSnapshot.jsp
  study/test/src/org/labkey/test/tests/study/QuerySnapshotTest.java
Labels: TeamCity test review complete, issue verification complete

#1185 Fb dataset from file test migration
  .gitattributes
  list/src/org/labkey/list/controllers/ListController.java
  study/gwtsrc/gwt/client/org/labkey/study/StudyApplication.java
  study/gwtsrc/gwt/client/org/labkey/study/dataset/client/DatasetImporter.java
  study/gwtsrc/gwt/client/org/labkey/study/dataset/client/DatasetService.java
  study/gwtsrc/gwt/client/org/labkey/study/dataset/client/DatasetServiceAsync.java
  study/gwtsrc/gwt/client/org/labkey/study/dataset/client/Designer.java
  study/gwtsrc/gwt/client/org/labkey/study/dataset/client/model/GWTDataset.java
  study/package-lock.json
  study/package.json
  study/src/org/labkey/study/StudyModule.java
  study/src/org/labkey/study/controllers/DatasetController.java
  study/src/org/labkey/study/controllers/DatasetImportServiceImpl.java
  study/src/org/labkey/study/controllers/DatasetServiceImpl.java
  study/src/org/labkey/study/controllers/StudyController.java
  study/src/org/labkey/study/model/DatasetDomainKind.java
  study/src/org/labkey/study/model/DatasetDomainKindProperties.java
  study/src/org/labkey/study/model/StudyManager.java
  study/src/org/labkey/study/view/StudyGWTView.java
  study/src/org/labkey/study/view/datasetDetails.jsp
  study/src/org/labkey/study/view/datasetVisibility.jsp
  study/src/org/labkey/study/view/importDataType.jsp
  study/src/org/labkey/study/view/manageTypes.jsp
  study/test/src/org/labkey/test/tests/study/AbstractStudyTimeKeyFieldTest.java
  study/test/src/org/labkey/test/tests/study/SharedStudyTest.java
  study/test/src/org/labkey/test/tests/study/StudyContinuousTest.java
  study/test/src/org/labkey/test/tests/study/StudyDateBasedTest.java
  study/test/src/org/labkey/test/tests/study/StudyExportTest.java
  study/test/src/org/labkey/test/tests/study/StudyManualTest.java
  study/test/src/org/labkey/test/tests/study/StudyScheduleTest.java
  study/test/src/org/labkey/test/tests/study/StudyTest.java
  study/webapp/study/StudyScheduleGrid.js
Labels: TeamCity test review complete

#1184 Item 6646: Issues List Def automated test conversion
  assay/package-lock.json
  assay/package.json
  core/package-lock.json
  core/package.json
  experiment/package-lock.json
  experiment/package.json
  internal/src/org/labkey/api/exp/property/DomainUtil.java
  issues/gwtsrc/org/labkey/issues/Designer.gwt.xml
  issues/gwtsrc/org/labkey/issues/client/GWTIssueDefinition.java
  issues/gwtsrc/org/labkey/issues/client/IssueDesigner.java
  issues/gwtsrc/org/labkey/issues/client/IssueDesignerLoader.java
  issues/gwtsrc/org/labkey/issues/client/IssueService.java
  issues/gwtsrc/org/labkey/issues/client/IssueServiceAsync.java
  issues/package-lock.json
  issues/package.json
  issues/src/client/Designer/Designer.tsx
  issues/src/org/labkey/issue/IssuesController.java
  issues/src/org/labkey/issue/IssuesModule.java
  issues/src/org/labkey/issue/actions/IssueServiceAction.java
  issues/src/org/labkey/issue/model/IssueManager.java
  issues/src/org/labkey/issue/model/IssuesListDefServiceImpl.java
  list/package-lock.json
  list/package.json
  query/package-lock.json
  query/package.json
  study/package-lock.json
  study/package.json
Labels: TeamCity test review complete, issue verification complete

#1198 Item 7333 - List designer issue fix targeting release20.3
  list/package-lock.json
  list/package.json
Labels: issue verification complete

#1211 Issue 40502: Dataset "Set default" view doesn't show custom views if dataset name and label differ
  study/src/org/labkey/study/controllers/StudyController.java
  study/src/org/labkey/study/reports/ReportManager.java
Labels: TeamCity test review complete

#1122 Issue 40347: UX Domain designer wrappers not supporting domain kind specific properties in the create case
  api/src/org/labkey/api/exp/api/DataClassDomainKindProperties.java
  assay/package-lock.json
  assay/package.json
  core/package-lock.json
  core/package.json
  experiment/package-lock.json
  experiment/package.json
  experiment/src/client/DataClassDesigner/DataClassDesigner.tsx
  experiment/src/client/SampleTypeDesigner/SampleTypeDesigner.tsx
  experiment/src/org/labkey/experiment/api/DataClassDomainKind.java
  experiment/src/org/labkey/experiment/controllers/property/PropertyController.java
  internal/src/org/labkey/api/exp/property/AbstractDomainKind.java
  internal/src/org/labkey/api/exp/property/DomainUtil.java
  internal/src/org/labkey/api/issues/AbstractIssuesListDefDomainKind.java
  internal/src/org/labkey/api/issues/IssuesListDefService.java
  internal/src/org/labkey/experiment/api/SampleSetDomainKind.java
  issues/package-lock.json
  issues/package.json
  issues/src/org/labkey/issue/model/IssuesListDefServiceImpl.java
  list/package-lock.json
  list/package.json
  list/src/client/Designer/Designer.tsx
  list/src/org/labkey/list/model/ListDomainKind.java
  list/src/org/labkey/list/model/ListManager.java
  query/package-lock.json
  query/package.json
  study/package-lock.json
  study/package.json
  study/src/client/DatasetDesigner/DatasetDesigner.tsx
  study/src/org/labkey/study/model/DatasetDomainKind.java
Labels: TeamCity test review complete

#1213 Item 7353: Remove PropertiesEditor test class and move related enums to FieldDefinition class
  study/test/src/org/labkey/test/tests/study/StudyPHIExportTest.java
  study/test/src/org/labkey/test/tests/study/StudyPublishTest.java
Labels: TeamCity test review complete

#1219 Misc domain designer fixes for 20.7
  assay/package-lock.json
  assay/package.json
  core/package-lock.json
  core/package.json
  experiment/package-lock.json
  experiment/package.json
  issues/package-lock.json
  issues/package.json
  list/package-lock.json
  list/package.json
  query/package-lock.json
  query/package.json
  study/package-lock.json
  study/package.json
Labels: TeamCity test review complete

#1229 Issue 40503: Luminex Levey-Jennings fix for cross container display/query of single point control calc and QC flag data
  experiment/src/org/labkey/experiment/api/ExpQCFlagTableImpl.java
Labels: needs TeamCity test review
