Repository LabKey/platform, pull requests merged in 2020-02, with the labels that each got.

#803 Issue 39628: LABKEY.Utils.encodeHtml change to, by default, return an empty string for values of undefined and null
  api/webapp/clientapi/core/Utils.js
Labels: TeamCity test review complete

#808 Issue 39341: Fix for specimen designer usage of data types that aren't supported for new domain field creation
  assay/package-lock.json
  assay/package.json
  experiment/package-lock.json
  experiment/package.json
Labels: TeamCity test review complete, issue verification complete

#814 Update core module to use shared webpack configs and devDependencies from platform
  .gitignore
  core/README.md
  core/build.gradle
  core/package-lock.json
  core/package.json
  core/postcss.config.js
  core/src/client/AuthenticationConfiguration/AuthenticationConfiguration.tsx
  core/src/client/AuthenticationConfiguration/authenticationConfiguration.css
  core/src/client/AuthenticationConfiguration/authenticationConfiguration.scss
  core/src/client/AuthenticationConfiguration/restoreBootstrapInCore.scss
  core/src/client/components/AuthRow.tsx
  core/src/client/components/DatabaseConfigurationModal.tsx
  core/src/client/components/DynamicConfigurationModal.tsx
  core/src/client/components/SSOFields.spec.tsx
  core/src/client/components/SSOFields.tsx
  core/src/client/components/__snapshots__/DatabaseConfigurationModal.spec.tsx.snap
  core/src/client/components/__snapshots__/DynamicConfigurationModal.spec.tsx.snap
  core/src/client/components/__snapshots__/SSOFields.spec.tsx.snap
  core/src/client/entryPoints.js
  core/test/jest.setup.ts
  core/tsconfig.json
  core/webpack/pages/app.template.html
  core/webpack/pages/app.view.template.xml
  core/webpack/pages/constants.js
  core/webpack/pages/dev.config.js
  core/webpack/pages/prod.config.js
  experiment/src/client/DomainDesigner/DomainDesigner.tsx
Labels: TeamCity test review complete, issue verification complete

#802 Issue 39609: Sample Manager: cannot delete a sample that had previously derived samples
  experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
Labels: issue verification complete

#830 Enable SimpleRedirectAction to redirect to whitelisted external hosts
  api/src/org/labkey/api/action/SimpleRedirectAction.java
  api/src/org/labkey/api/util/ReturnURLString.java
  api/src/org/labkey/api/util/URLHelper.java
Labels: code review complete

#847 Issue 33393: hide “Change Email” button from trial instance (or any instance set as to auto redirect to SSO auth)
  core/src/org/labkey/core/user/UserController.java
Labels: TeamCity test review complete

#849 Issue 38439: Fix for file root change display of migrate files option on error reshow
  core/src/org/labkey/core/admin/view/filesProjectSettings.jsp
Labels: TeamCity test review complete

#889 Fix for DomainDesignerTest failures related to List Designer changes
  core/package-lock.json
  experiment/src/client/DomainDesigner/DomainDesigner.tsx
Labels: TeamCity test review complete
