Repository LabKey/platform, pull requests merged in 2020-01, with the labels that each got.

#711 Assays aren't indexed or unindexed in a short enough period
  api/src/org/labkey/api/assay/AssayService.java
  api/src/org/labkey/api/exp/api/ExpProtocol.java
  assay/src/org/labkey/assay/AssayManager.java
  experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
Labels: TeamCity test review complete, code review complete, issue verification complete

#730 Issue 38874: Update Bar chart default hover tooltip to include chart label and sublabel
  internal/webapp/vis/src/internal/D3Renderer.js
Labels: TeamCity test review complete

#727 Item 6506: API Action updates to support user management in Sample Manager app
  api/src/org/labkey/api/util/PageFlowUtil.java
  api/webapp/clientapi/core/Security.js
  core/src/org/labkey/core/security/SecurityApiActions.java
  core/src/org/labkey/core/security/SecurityController.java
  core/src/org/labkey/core/user/UserController.java
  core/src/org/labkey/core/user/deactivateUsers.jsp
  core/src/org/labkey/core/user/deleteUsers.jsp
  core/webapp/Security/panel/PolicyEditor.js
Labels: TeamCity test review complete

#738 Omit some property types from the field designer for SM
  assay/package-lock.json
  assay/package.json
  assay/src/client/AssayDataImport/AssayDataImport.tsx
  core/package-lock.json
  experiment/package-lock.json
  experiment/package.json
Labels: needs TeamCity test review, needs issue verification

#737 Item 6571: Change to support Sample Manager new user email content and hosted server setup
  api/webapp/clientapi/core/Security.js
  assay/package-lock.json
  assay/package.json
  core/src/org/labkey/core/CoreModule.java
  core/src/org/labkey/core/login/LoginController.java
  core/src/org/labkey/core/login/PasswordRule.java
  core/src/org/labkey/core/login/setPassword.jsp
  core/src/org/labkey/core/security/SecurityApiActions.java
  experiment/package-lock.json
  experiment/package.json
Labels: TeamCity test review complete, issue verification complete

#736 Item 6630 : FileProperties designer migration
  filecontent/gwtsrc/org/labkey/filecontent/designer/FilePropertiesDesigner.gwt.xml
  filecontent/gwtsrc/org/labkey/filecontent/designer/client/FilePropertiesDesigner.java
  filecontent/gwtsrc/org/labkey/filecontent/designer/client/FilePropertiesService.java
  filecontent/gwtsrc/org/labkey/filecontent/designer/client/FilePropertiesServiceAsync.java
  filecontent/src/org/labkey/filecontent/FileContentController.java
  filecontent/src/org/labkey/filecontent/FilePropertiesDomainKind.java
  filecontent/src/org/labkey/filecontent/FilePropertiesServiceImpl.java
  filecontent/webapp/File/panel/EditCustomFileProps.js
Labels: TeamCity test review complete, issue verification complete

#756 ExperimentController.AbstractDeleteAPIAction - restore response object from deleteObjects()
  experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
Labels: TeamCity test review complete

#765 Share webpack configs and template files for modules within the platform repository
  assay/package.json
  assay/src/client/entryPoints.js
  assay/webpack/app.template.html
  assay/webpack/app.view.template.xml
  assay/webpack/dev.config.js
  experiment/README.md
  experiment/package.json
  experiment/postcss.config.js
  experiment/src/client/entryPoints.js
  experiment/tsconfig.json
  experiment/webpack/constants.js
  experiment/webpack/prod.config.js
  postcss.config.js
  tsconfig.json
  webpack/app.template.html
  webpack/app.view.template.xml
  webpack/constants.js
  webpack/dev.config.js
  webpack/prod.config.js
Labels: TeamCity test review complete

#782 Share package.json devDependencies for prod React page builds within the platform repository
  .gitignore
  assay/build.gradle
  assay/package-lock.json
  assay/package.json
  build.gradle
  experiment/build.gradle
  experiment/package-lock.json
  experiment/package.json
  package-lock.json
  package.json
  webpack/constants.js
  webpack/dev.config.js
  webpack/prod.config.js
Labels: TeamCity test review complete
