Repository LabKey/platform, pull requests merged in 2020-09, with the labels that each got.

#1553 Item 7713: Add SQL dialect helper for getNumericCast()
  api/src/org/labkey/api/data/dialect/SqlDialect.java
  bigiron/src/org/labkey/bigiron/mssql/BaseMicrosoftSqlServerDialect.java
Labels: needs TeamCity test review

#1563 Item 7840: @labkey/components package update and switch build to using scss files instead of components.css
  assay/package-lock.json
  assay/package.json
  assay/src/client/AssayDataImport/AssayDataImport.tsx
  assay/src/client/AssayDataImport/assayDataImport.scss
  assay/src/client/AssayDesigner/AssayDesigner.scss
  assay/src/client/AssayDesigner/AssayDesigner.tsx
  core/package-lock.json
  core/package.json
  core/src/client/AuthenticationConfiguration/AuthenticationConfiguration.tsx
  core/src/client/AuthenticationConfiguration/authenticationConfiguration.scss
  core/src/client/ErrorHandler/ErrorHandler.tsx
  core/src/client/ErrorHandler/errorHandler.scss
  core/src/client/LabKeyUIComponentsPage/LabKeyUIComponentsPage.scss
  core/src/client/LabKeyUIComponentsPage/LabKeyUIComponentsPage.tsx
  experiment/package-lock.json
  experiment/package.json
  experiment/src/client/DataClassDesigner/DataClassDesigner.scss
  experiment/src/client/DataClassDesigner/DataClassDesigner.tsx
  experiment/src/client/DomainDesigner/DomainDesigner.scss
  experiment/src/client/DomainDesigner/DomainDesigner.tsx
  experiment/src/client/RunGraph/RunGraph.scss
  experiment/src/client/RunGraph/RunGraph.tsx
  experiment/src/client/SampleTypeDesigner/SampleTypeDesigner.scss
  experiment/src/client/SampleTypeDesigner/SampleTypeDesigner.tsx
  issues/package-lock.json
  issues/package.json
  issues/src/client/Designer/Designer.scss
  issues/src/client/Designer/Designer.tsx
  list/package-lock.json
  list/package.json
  list/src/client/Designer/Designer.scss
  list/src/client/Designer/Designer.tsx
  package-lock.json
  package.json
  query/package-lock.json
  query/package.json
  query/src/client/QueryMetadataEditor/QueryMetadataEditor.tsx
  query/src/client/QueryMetadataEditor/queryMetadataEditor.scss
  study/package-lock.json
  study/package.json
  study/src/client/DatasetDesigner/DatasetDesigner.scss
  study/src/client/DatasetDesigner/DatasetDesigner.tsx
Labels: TeamCity test review complete, issue verification complete

#1581 Mark PostgreSQL 13.x as tested. Add enum constant for JDK 16.
  api/src/org/labkey/api/module/JavaVersion.java
  core/src/org/labkey/core/dialect/PostgreSqlVersion.java
Labels: TeamCity test review complete

#1580 Mark OpenJDK 15 as tested and OpenJDK 13 as deprecated (#1577)
  api/src/org/labkey/api/module/JavaVersion.java
Labels: TeamCity test review complete

#1591 Update to latest @labkey/components package with changes for internal component restructure
  assay/package-lock.json
  assay/package.json
  core/package-lock.json
  core/package.json
  experiment/package-lock.json
  experiment/package.json
  issues/package-lock.json
  issues/package.json
  list/package-lock.json
  list/package.json
  query/package-lock.json
  query/package.json
  study/package-lock.json
  study/package.json
Labels: TeamCity test review complete

#1590 Issue 39386: Importing sample type design XAR makes first field required
  api/src/org/labkey/api/exp/api/ExpSampleType.java
  api/src/org/labkey/api/exp/api/SampleTypeDomainKindProperties.java
  experiment/src/org/labkey/experiment/XarExporter.java
  experiment/src/org/labkey/experiment/XarReader.java
  experiment/src/org/labkey/experiment/api/ExpMaterialTableImpl.java
  experiment/src/org/labkey/experiment/api/ExpSampleTypeImpl.java
Labels: issue verification complete

#1601 Issue 41431: Misc test fixes on domain designer conditional format dialog and buttons
  assay/package-lock.json
  assay/package.json
  core/package-lock.json
  core/package.json
  experiment/package-lock.json
  experiment/package.json
  issues/package-lock.json
  issues/package.json
  list/package-lock.json
  list/package.json
  query/package-lock.json
  query/package.json
  study/package-lock.json
  study/package.json
Labels: TeamCity test review complete
