Repository LabKey/platform, pull requests merged in 2020-03, with the labels that each got.

#914 Item 6640: Fix for List Designer issues targeting LabKey release 20.3
  assay/package-lock.json
  assay/package.json
  core/package-lock.json
  core/package.json
  experiment/package-lock.json
  experiment/package.json
  experiment/src/org/labkey/experiment/api/property/DomainPropertyImpl.java
  list/package-lock.json
  list/package.json
  list/src/org/labkey/list/ListModule.java
  list/src/org/labkey/list/controllers/ListController.java
  list/src/org/labkey/list/model/ListManager.java
  list/src/org/labkey/list/model/ListManagerSchema.java
Labels: TeamCity test review complete

#932 Issue 39926: GetColumnSummaryStatsAction - add null check for aggregate results and return better error message
  query/src/org/labkey/query/controllers/QueryController.java
Labels: TeamCity test review complete

#944 Update to @labkey/components package version which includes hotfix changes from 20.3
  assay/package-lock.json
  assay/package.json
  core/package-lock.json
  core/package.json
  experiment/package-lock.json
  experiment/package.json
  list/package-lock.json
  list/package.json
Labels: TeamCity test review complete

#894 Merge Sample Type UI creation and editing into one page
  .gitignore
  api/src/org/labkey/api/exp/api/ExpSampleSet.java
  api/src/org/labkey/api/exp/api/SampleSetService.java
  api/src/org/labkey/api/exp/api/SampleTypeDomainKindProperties.java
  api/src/org/labkey/api/exp/property/DomainKind.java
  assay/package-lock.json
  assay/package.json
  assay/src/org/labkey/assay/PlateBasedAssaySampleSetDomainKind.java
  core/package-lock.json
  core/package.json
  experiment/package-lock.json
  experiment/package.json
  experiment/src/client/SampleTypeDesigner/SampleTypeDesigner.tsx
  experiment/src/client/SampleTypeDesigner/app.tsx
  experiment/src/client/SampleTypeDesigner/dev.tsx
  experiment/src/client/SampleTypeDesigner/sampleTypeDesigner.scss
  experiment/src/client/entryPoints.js
  experiment/src/org/labkey/experiment/SampleSetWebPart.java
  experiment/src/org/labkey/experiment/api/ExpSampleSetImpl.java
  experiment/src/org/labkey/experiment/api/SampleSetServiceImpl.java
  experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
  experiment/src/org/labkey/experiment/controllers/property/PropertyController.java
  experiment/src/org/labkey/experiment/createSampleSet.jsp
  experiment/test/src/org/labkey/test/tests/experiment/VocabularyViewSupportTest.java
  internal/src/org/labkey/api/query/SimpleTableDomainKind.java
  internal/src/org/labkey/experiment/api/SampleSetDomainKind.java
  list/package-lock.json
  list/package.json
  study/test/src/org/labkey/test/tests/experiment/ExpSchemaPropagateFilterTest.java
  study/test/src/org/labkey/test/tests/experiment/ExperimentAPITest.java
Labels: needs TeamCity test review, needs issue verification

#918 Item 6835: Data Class designer updates for use in Sample Manager
  .gitignore
  api/src/org/labkey/api/exp/api/DataClassDomainKindProperties.java
  api/src/org/labkey/api/exp/api/ExpDataClass.java
  api/src/org/labkey/api/exp/api/ExperimentService.java
  api/src/org/labkey/api/exp/property/DomainKind.java
  api/src/org/labkey/api/exp/query/ExpSchema.java
  assay/package-lock.json
  assay/package.json
  core/package-lock.json
  core/package.json
  experiment/package-lock.json
  experiment/package.json
  experiment/src/client/DataClassDesigner/DataClassDesigner.tsx
  experiment/src/client/DataClassDesigner/app.tsx
  experiment/src/client/DataClassDesigner/dev.tsx
  experiment/src/client/DomainDesigner/DomainDesigner.tsx
  experiment/src/client/entryPoints.js
  experiment/src/org/labkey/experiment/api/DataClassDomainKind.java
  experiment/src/org/labkey/experiment/api/ExpDataClassDataTestCase.java
  experiment/src/org/labkey/experiment/api/ExpDataClassImpl.java
  experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
  experiment/src/org/labkey/experiment/api/LineagePerfTest.java
  experiment/src/org/labkey/experiment/api/LineageTest.java
  experiment/src/org/labkey/experiment/api/UniqueValueCounterTestCase.java
  experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
  internal/src/org/labkey/api/exp/property/AbstractDomainKind.java
  internal/src/org/labkey/api/exp/property/DomainUtil.java
  list/package-lock.json
  list/package.json
  list/src/org/labkey/list/model/ListDomainKind.java
  query/package-lock.json
  query/package.json
Labels: TeamCity test review complete, issue verification complete

#997 Item 7002: Refactor domain designer components to share more with base components
  api/gwtsrc/org/labkey/api/gwt/client/model/GWTDomain.java
  api/src/org/labkey/api/exp/property/DomainKind.java
  assay/package-lock.json
  assay/package.json
  assay/src/client/AssayDataImport/AssayDataImport.tsx
  core/package-lock.json
  core/package.json
  experiment/package-lock.json
  experiment/package.json
  experiment/src/client/SampleTypeDesigner/SampleTypeDesigner.tsx
  experiment/src/client/SampleTypeDesigner/app.tsx
  experiment/src/client/SampleTypeDesigner/dev.tsx
  experiment/src/client/SampleTypeDesigner/sampleTypeDesigner.scss
  experiment/src/client/entryPoints.js
  experiment/src/org/labkey/experiment/api/SampleSetServiceImpl.java
  experiment/src/org/labkey/experiment/controllers/property/PropertyController.java
  internal/src/org/labkey/experiment/api/SampleSetDomainKind.java
  list/package-lock.json
  list/package.json
  query/package-lock.json
  query/package.json
Labels: TeamCity test review complete, issue verification complete

#1005 Remove List's gwt src & its references, and the experimental flag.
  list/gwtsrc/org/labkey/list/Designer.gwt.xml
  list/gwtsrc/org/labkey/list/client/GWTList.java
  list/gwtsrc/org/labkey/list/client/ListDesigner.java
  list/gwtsrc/org/labkey/list/client/ListDesignerLoader.java
  list/gwtsrc/org/labkey/list/client/ListEditorService.java
  list/gwtsrc/org/labkey/list/client/ListEditorServiceAsync.java
  list/src/org/labkey/list/ListModule.java
  list/src/org/labkey/list/controllers/ListController.java
  list/src/org/labkey/list/model/ListDefinitionImpl.java
  list/src/org/labkey/list/model/ListDomainKind.java
  list/src/org/labkey/list/model/ListDomainKindProperties.java
  list/src/org/labkey/list/model/ListEditorServiceImpl.java
  list/src/org/labkey/list/model/ListManager.java
  list/src/org/labkey/list/model/ListManagerSchema.java
Labels: needs TeamCity test review
