Repository LabKey/platform, pull requests merged in 2020-04, with the labels that each got.

#1017 Remove unused code from the BaseSampleSetAction now that it has been converted to new sample type designer workflow
  experiment/src/org/labkey/experiment/api/SampleSetServiceImpl.java
  experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
Labels: TeamCity test review complete

#1030 Replace platform React page usages of LABKEY with getServerContext() from @labkey/api package
  assay/package.json
  assay/src/client/AssayDataImport/AssayDataImport.tsx
  assay/src/client/AssayDataImport/AssayRunForm.tsx
  assay/src/client/AssayDataImport/app.tsx
  assay/src/client/AssayDataImport/dev.tsx
  assay/src/client/AssayDesigner/AssayDesigner.tsx
  assay/src/client/AssayDesigner/app.tsx
  assay/src/client/AssayDesigner/dev.tsx
  assay/src/client/typings/main.d.ts
  core/package.json
  core/src/client/AuthenticationConfiguration/AuthenticationConfiguration.tsx
  core/src/client/LabKeyUIComponentsPage/DetailPage.tsx
  core/src/client/LabKeyUIComponentsPage/LabKeyUIComponentsPage.tsx
  core/src/client/LabKeyUIComponentsPage/NavigationBarPage.tsx
  core/src/client/LabKeyUIComponentsPage/PermissionAssignmentsPage.tsx
  core/src/client/LabKeyUIComponentsPage/SiteUsersGridPanelPage.tsx
  core/src/client/components/AuthConfigMasterPanel.tsx
  core/src/client/components/AuthRow.tsx
  core/src/client/components/DatabaseConfigurationModal.tsx
  core/src/client/components/DragAndDropPane.tsx
  core/src/client/components/DynamicConfigurationModal.tsx
  core/src/client/components/DynamicFields.tsx
  core/src/client/components/models.ts
  experiment/package.json
  experiment/src/client/DataClassDesigner/DataClassDesigner.tsx
  experiment/src/client/DomainDesigner/DomainDesigner.tsx
  experiment/src/client/DomainDesigner/domainDesigner.scss
  experiment/src/client/SampleTypeDesigner/SampleTypeDesigner.tsx
  experiment/src/client/typings/main.d.ts
  list/package.json
  list/src/client/Designer/Designer.tsx
  list/src/client/typings/main.d.ts
  query/package.json
  query/src/client/QueryMetadataEditor/QueryMetadataEditor.tsx
  query/src/client/QueryMetadataEditor/app.tsx
  query/src/client/QueryMetadataEditor/components/AliaseFieldModal.tsx
  query/src/client/QueryMetadataEditor/dev.tsx
  query/src/client/QueryMetadataEditor/queryMetadataEditor.scss
  query/src/client/typings/main.d.ts
Labels: TeamCity test review complete

#1033 Issue 39848: List designer "export and print" checkbox not properly hiding print button on list grid
  api/src/org/labkey/api/query/QueryView.java
Labels: TeamCity test review complete

#988 6883: MultiAuth Followup Work
  core/package-lock.json
  core/package.json
  core/src/client/AuthenticationConfiguration/AuthenticationConfiguration.spec.tsx
  core/src/client/AuthenticationConfiguration/AuthenticationConfiguration.tsx
  core/src/client/AuthenticationConfiguration/constants.ts
  core/src/client/components/AuthConfigMasterPanel.spec.tsx
  core/src/client/components/AuthConfigMasterPanel.tsx
  core/src/client/components/AuthRow.spec.tsx
  core/src/client/components/AuthRow.tsx
  core/src/client/components/DatabaseConfigurationModal.tsx
  core/src/client/components/DragAndDropPane.tsx
  core/src/client/components/DynamicConfigurationModal.spec.tsx
  core/src/client/components/DynamicConfigurationModal.tsx
  core/src/client/components/DynamicFields.tsx
  core/src/client/components/GlobalSettings.spec.tsx
  core/src/client/components/GlobalSettings.tsx
  core/src/client/components/__snapshots__/AuthConfigMasterPanel.spec.tsx.snap
  core/src/client/components/__snapshots__/AuthRow.spec.tsx.snap
  core/src/client/components/__snapshots__/DynamicConfigurationModal.spec.tsx.snap
  core/src/client/components/__snapshots__/GlobalSettings.spec.tsx.snap
  core/src/client/components/models.ts
  core/test/data.ts
Labels: TeamCity test review complete, needs TeamCity test review

#1045 Fix for NPE in DomainImpl when trying to access domain properties after they have been changed/deleted
  experiment/src/org/labkey/experiment/api/property/DomainImpl.java
Labels: TeamCity test review complete

#1075 Issue 39803: Use redirectURL.getURIString() for LogoutApiAction response
  core/src/org/labkey/core/login/LoginController.java
Labels: TeamCity test review complete

#1071 Issue 40168: Lookups from Assay to Sample Sets in a different container fail to resolve sample on assay run upload
  api/src/org/labkey/api/assay/AbstractAssayTsvDataHandler.java
Labels: TeamCity test review complete, issue verification complete

#1064 Item 6961: DataClassDesigner updates for LKS
  api/src/org/labkey/api/exp/api/DataClassDomainKindProperties.java
  api/src/org/labkey/api/exp/api/ExpDataClass.java
  api/src/org/labkey/api/exp/api/ExpSampleSet.java
  api/src/org/labkey/api/exp/api/ExperimentUrls.java
  api/src/org/labkey/api/security/permissions/DesignDataClassPermission.java
  api/src/org/labkey/api/security/roles/FolderAdminRole.java
  assay/package-lock.json
  assay/package.json
  core/package-lock.json
  core/package.json
  experiment/package-lock.json
  experiment/package.json
  experiment/src/client/DataClassDesigner/DataClassDesigner.tsx
  experiment/src/org/labkey/experiment/DataClassWebPart.java
  experiment/src/org/labkey/experiment/SampleSetWebPart.java
  experiment/src/org/labkey/experiment/api/DataClassDomainKind.java
  experiment/src/org/labkey/experiment/api/ExpDataClassImpl.java
  experiment/src/org/labkey/experiment/api/ExpDataClassTableImpl.java
  experiment/src/org/labkey/experiment/api/ExpSampleSetImpl.java
  experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
  experiment/src/org/labkey/experiment/createDataClassFromTemplate.jsp
  experiment/src/org/labkey/experiment/insertDataClass.jsp
  internal/src/org/labkey/api/exp/property/DomainTemplateGroup.java
  internal/src/org/labkey/experiment/api/SampleSetDomainKind.java
  list/package-lock.json
  list/package.json
  query/package-lock.json
  query/package.json
Labels: TeamCity test review complete, issue verification complete

#1095 Fix test failures related to AbstractQueryImportAction.importData method signature change
  api/src/org/labkey/api/query/AbstractQueryImportAction.java
  list/src/org/labkey/list/controllers/ListController.java
  study/src/org/labkey/study/controllers/StudyController.java
  study/src/org/labkey/study/controllers/specimen/SpecimenController.java
Labels: TeamCity test review complete

#1097 Issue 40123: Cannot view the lineage of a source on MS-SQL when medImmune module is included
  core/package-lock.json
  core/package.json
  experiment/src/org/labkey/experiment/api/ExpDataImpl.java
Labels: TeamCity test review complete

#1099 Incorporate fix for LABKEY.Assay.getStudyNabGraphURL
  core/package-lock.json
  core/package.json
Labels: TeamCity test review complete
