Repository LabKey/platform, pull requests merged in 2021-02, with the labels that each got.

#2001 Item 8335: LabKey product navigation header icon and menu
  api/src/org/labkey/api/util/PageFlowUtil.java
  api/src/org/labkey/api/view/template/errorView.jsp
  api/webapp/clientapi/dom/Portal.js
  assay/package-lock.json
  assay/package.json
  core/api-src/org/labkey/api/products/ProductMenuProvider.java
  core/api-src/org/labkey/api/products/ProductRegistry.java
  core/package-lock.json
  core/package.json
  core/src/client/ProductNavigation/ProductNavigation.tsx
  core/src/client/ProductNavigation/app.tsx
  core/src/client/ProductNavigation/dev.tsx
  core/src/client/ProductNavigation/productNavigation.scss
  core/src/client/entryPoints.js
  core/src/org/labkey/core/admin/AdminController.java
  core/src/org/labkey/core/products/ProductController.java
  core/src/org/labkey/core/view/template/bootstrap/header.jsp
  experiment/package-lock.json
  experiment/package.json
  internal/webapp/_images/mobile-logo-seattle.svg
  issues/package-lock.json
  issues/package.json
  list/package-lock.json
  list/package.json
  query/package-lock.json
  query/package.json
  study/package-lock.json
  study/package.json
Labels: TeamCity test review complete, issue verification complete

#2026 8049: Summary View Manual Testing Tweaks
  assay/package-lock.json
  assay/package.json
  core/package-lock.json
  core/package.json
  experiment/package-lock.json
  experiment/package.json
  issues/package-lock.json
  issues/package.json
  list/package-lock.json
  list/package.json
  query/package-lock.json
  query/package.json
  study/package-lock.json
  study/package.json
Labels: TeamCity test review complete, needs TeamCity test review

#2033 @labkey/components package update for bundle optimizations
  assay/package-lock.json
  assay/package.json
  core/package-lock.json
  core/package.json
  experiment/package-lock.json
  experiment/package.json
  issues/package-lock.json
  issues/package.json
  list/package-lock.json
  list/package.json
  query/package-lock.json
  query/package.json
  study/package-lock.json
  study/package.json
Labels: TeamCity test review complete

#2034 Issue 42534: Move header.jsp JS code related to Product Navigation menu to core/ProductNavigationHeader.js
  core/src/org/labkey/core/view/template/bootstrap/header.jsp
  core/webapp/core/ProductNavigationHeader.js
Labels: TeamCity test review complete

#2036 Issue40946: Updates to secure message board options
  announcements/resources/schemas/dbscripts/postgresql/comm-21.000-21.001.sql
  announcements/resources/schemas/dbscripts/sqlserver/comm-21.000-21.001.sql
  announcements/src/org/labkey/announcements/AnnouncementModule.java
  announcements/src/org/labkey/announcements/customize.jsp
  announcements/src/org/labkey/announcements/insert.jsp
  announcements/src/org/labkey/announcements/model/AnnouncementDigestProvider.java
  announcements/src/org/labkey/announcements/model/AnnouncementManager.java
  announcements/src/org/labkey/announcements/query/AnnouncementSchema.java
  announcements/src/org/labkey/announcements/query/AnnouncementTable.java
  announcements/src/org/labkey/announcements/respond.jsp
  announcements/src/org/labkey/announcements/update.jsp
  internal/src/org/labkey/api/announcements/DiscussionService.java
Labels: needs TeamCity test review

#2037 Item 8583: Ontology concept picker integration for field editor concept annotation feature
  api/src/org/labkey/api/data/DisplayColumn.java
  assay/package-lock.json
  assay/package.json
  core/package-lock.json
  core/package.json
  core/src/client/LabKeyUIComponentsPage/LabKeyUIComponentsPage.tsx
  core/src/client/LabKeyUIComponentsPage/OntologyBrowserPage.tsx
  experiment/package-lock.json
  experiment/package.json
  issues/package-lock.json
  issues/package.json
  list/package-lock.json
  list/package.json
  query/package-lock.json
  query/package.json
  study/package-lock.json
  study/package.json
Labels: TeamCity test review complete, issue verification complete
