Repository LabKey/platform, pull requests merged in 2021-12, with the labels that each got.

#2816 Issue #44384: Folder w/ Sample Type can not be used as template
  experiment/src/org/labkey/experiment/samples/SampleTypeAndDataClassFolderImporter.java
Labels: issue verification complete, needs code review, needs TeamCity test review

#2835 Item 9627: TextChoiceValidator and usage for rendering select input for LKS insert/update form and app update forms
  api/gwtsrc/org/labkey/api/gwt/client/model/PropertyValidatorType.java
  api/src/org/labkey/api/data/DataColumn.java
  api/src/org/labkey/api/data/JsonWriter.java
  api/src/org/labkey/api/exp/property/PropertyService.java
  core/package-lock.json
  core/package.json
  experiment/src/org/labkey/experiment/ExperimentModule.java
  experiment/src/org/labkey/experiment/api/property/PropertyServiceImpl.java
  experiment/src/org/labkey/experiment/api/property/RegExValidator.java
  experiment/src/org/labkey/experiment/api/property/TextChoiceValidator.java
Labels: issue verification complete, TeamCity test review complete

#2829 Issue 44428: Export and publish lists by default
  list/src/org/labkey/list/model/FolderListWriter.java
  study/test/src/org/labkey/test/tests/study/StudyPublishTest.java
  study/webapp/study/StudyWizard.js
Labels: TeamCity test review complete

#2876 Item 9758: Field editor "Text Choice" data type and UI to create, update, delete field options/values
  api/gwtsrc/org/labkey/api/gwt/client/model/GWTDomain.java
  api/src/org/labkey/api/assay/AssayService.java
  api/src/org/labkey/api/data/ColumnRenderPropertiesImpl.java
  api/src/org/labkey/api/data/DataColumn.java
  api/src/org/labkey/api/exp/property/DomainKind.java
  assay/api-src/org/labkey/api/assay/AssayDomainKind.java
  assay/src/org/labkey/assay/AssayManager.java
  assay/src/org/labkey/assay/DefaultAssayDomainKind.java
  assay/src/org/labkey/assay/PlateBasedAssaySampleTypeDomainKind.java
  core/package-lock.json
  core/package.json
  core/src/org/labkey/core/query/UsersDomainKind.java
  experiment/src/org/labkey/experiment/ExperimentModule.java
  experiment/src/org/labkey/experiment/api/property/TextChoiceValidator.java
  internal/src/org/labkey/api/exp/property/DomainUtil.java
  internal/src/org/labkey/api/issues/AbstractIssuesListDefDomainKind.java
  study/api-src/org/labkey/api/specimen/model/AbstractSpecimenDomainKind.java
  study/src/org/labkey/study/model/StudyDomainKind.java
Labels: issue verification complete, TeamCity test review complete

#2889 Issue 44535: Export displayOrder property for views
  api/src/org/labkey/api/reports/report/ReportDescriptor.java
Labels: needs code review, needs issue verification, needs TeamCity test review

#2897 Issue 44203: Assay import sample lookup try/catch to show failed sample remap error to user instead of throwing
  api/src/org/labkey/api/assay/AbstractAssayTsvDataHandler.java
Labels: TeamCity test review complete

#2903 Item 9782: Text Choice data type support for field editor updates to in use values
  api/gwtsrc/org/labkey/api/gwt/client/model/GWTPropertyValidator.java
  api/src/org/labkey/api/assay/AssayService.java
  api/src/org/labkey/api/exp/property/DomainKind.java
  assay/api-src/org/labkey/api/assay/AssayDomainKind.java
  assay/src/org/labkey/assay/AssayManager.java
  core/package-lock.json
  core/package.json
  experiment/src/org/labkey/experiment/api/DataClassDomainKind.java
  experiment/src/org/labkey/experiment/api/property/DomainImpl.java
  experiment/src/org/labkey/experiment/types/typeDetails.jsp
  internal/src/org/labkey/api/exp/property/DomainTemplate.java
  internal/src/org/labkey/api/exp/property/DomainUtil.java
  internal/src/org/labkey/api/issues/AbstractIssuesListDefDomainKind.java
  internal/src/org/labkey/experiment/api/SampleTypeDomainKind.java
  list/src/org/labkey/list/model/ListDomainKind.java
  study/src/org/labkey/study/assay/StudyPublishManager.java
  study/src/org/labkey/study/model/DatasetDomainKind.java
Labels: issue verification complete, TeamCity test review complete
