Repository LabKey/platform, pull requests merged in 2021-05, with the labels that each got.

#2254 Remove unnecessary main.d.ts file
  pipeline/src/client/CreatePipelineTrigger/typings/main.d.ts
Labels: TeamCity test review complete

#2261 Sample Type Polish: Test Fixes
  api/src/org/labkey/api/exp/query/SamplesSchema.java
  assay/api-src/org/labkey/api/assay/AssayResultTable.java
  experiment/src/org/labkey/experiment/ExpDataIterators.java
  experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
  experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
Labels: needs TeamCity test review

#2265 Issue 43107: Add back strictFieldValidation property for study dataset and data class domain creation
  api/src/org/labkey/api/exp/api/DataClassDomainKindProperties.java
  experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
  study/src/org/labkey/study/model/DatasetDomainKind.java
  study/src/org/labkey/study/model/DatasetDomainKindProperties.java
Labels: TeamCity test review complete, issue verification complete

#2284 Item 8897: Compliance settings option to hide page background content on invalid session modal
  api/src/org/labkey/api/ApiModule.java
  api/src/org/labkey/api/compliance/ComplianceService.java
  api/src/org/labkey/api/data/Container.java
  api/webapp/clientapi/dom/Utils.js
  api/webapp/clientapi/dom/WebSocket.js
  core/package-lock.json
  core/package.json
  core/src/org/labkey/core/view/template/bootstrap/pageTemplate.jsp
Labels: TeamCity test review complete, issue verification complete
