Repository LabKey/platform, pull requests merged in 2021-01, with the labels that each got.

#1861 @labkey/build package update to replace postcss.config.js file with inline webpack postcss-loader config
  assay/package-lock.json
  assay/package.json
  core/package-lock.json
  core/package.json
  experiment/package-lock.json
  experiment/package.json
  issues/package-lock.json
  issues/package.json
  list/package-lock.json
  list/package.json
  postcss.config.js
  query/package-lock.json
  query/package.json
  study/package-lock.json
  study/package.json
Labels: TeamCity test review complete

#1868 Issue 41864: DataRegion column analytics updates to lazy load Ext4 and vis dependencies
  api/webapp/clientapi/dom/DataRegion.js
  query/src/org/labkey/query/analytics/SummaryStatisticsAnalyticsProvider.java
  query/webapp/query/ColumnSummaryStatistics.js
  visualization/resources/views/querySummary.view.xml
  visualization/resources/web/vis/ColumnVisualizationAnalytics.js
  visualization/resources/web/vis/ColumnVisualizationAnalytics.lib.xml
  visualization/src/org/labkey/visualization/report/DimensionBarChartAnalyticsProvider.java
  visualization/src/org/labkey/visualization/report/DimensionPieChartAnalyticsProvider.java
  visualization/src/org/labkey/visualization/report/MeasureBoxPlotAnalyticsProvider.java
Labels: TeamCity test review complete

#1874 Data region fix for "Delete All Rows" to load Ext4 library on click
  api/src/org/labkey/api/query/QueryView.java
Labels: TeamCity test review complete

#1875 Data region fixes to load Ext4 library now that it isn't always on the page
  api/src/org/labkey/api/query/excelExportOptions.jsp
  api/src/org/labkey/api/query/textExportOptions.jsp
Labels: TeamCity test review complete

#1876 @labkey/build version update to remove postcss-loader
  assay/package-lock.json
  assay/package.json
  core/package-lock.json
  core/package.json
  experiment/package-lock.json
  experiment/package.json
  issues/package-lock.json
  issues/package.json
  list/package-lock.json
  list/package.json
  query/package-lock.json
  query/package.json
  study/package-lock.json
  study/package.json
Labels: TeamCity test review complete

#1780 8012: Field Editor Row Selection
  assay/package-lock.json
  assay/package.json
  core/package-lock.json
  core/package.json
  experiment/package-lock.json
  experiment/package.json
  issues/package-lock.json
  issues/package.json
  list/package-lock.json
  list/package.json
  query/package-lock.json
  query/package.json
  study/package-lock.json
  study/package.json
Labels: needs TeamCity test review

#1919 DataRegion fix for Ext4 dependency loading related to prompt to save session view
  api/webapp/clientapi/dom/DataRegion.js
Labels: TeamCity test review complete

#1917 Item 8357: LKFM Inventory data folder archive export/import
  api/schemas/folder.xsd
  api/src/org/labkey/api/admin/FolderArchiveDataTypes.java
  experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
  experiment/src/org/labkey/experiment/api/property/DomainImpl.java
  experiment/src/org/labkey/experiment/api/property/DomainPropertyManager.java
  experiment/src/org/labkey/experiment/samples/SampleTypeAndDataClassFolderImporter.java
Labels: TeamCity test review complete, issue verification complete

#1927 Issue 42216: Fix for logout event notification issue with different user sessions
  api/src/org/labkey/api/security/AuthNotify.java
  api/src/org/labkey/api/security/AuthenticationManager.java
  api/webapp/clientapi/dom/WebSocket.js
Labels: TeamCity test review complete, issue verification complete

#1943 Issue 42302: Group names rendered unencoded in permissions page
  core/webapp/Security/panel/GroupPicker.js
  core/webapp/Security/window/UserInfoPopup.js
Labels: TeamCity test review complete
