Repository LabKey/platform, pull requests merged in 2022-05, with the labels that each got.

#3304 Issue 45374: LKSM issues when site "default display format for numbers" is set
  core/package-lock.json
  core/package.json
  experiment/src/org/labkey/experiment/api/ExpSampleTypeTableImpl.java
Labels: TeamCity test review complete

#3310 Issue 45355: More descriptive Data Class action buttons
  experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
Labels: needs TeamCity test review

#3322 Issue 45264: Include full +/- 3 standard deviation range in QC plots
  internal/webapp/vis/src/plot.js
Labels: TeamCity test review complete

#3321 Issue 45421: User impersonation combo box is selecting wrong user when deactivated user is in the list
  internal/webapp/Impersonate.js
Labels: TeamCity test review complete

#3331 Issue 45212: Changing display column of a lookup doesn't order alphabetically
  api/src/org/labkey/api/data/AbstractTableInfo.java
Labels: TeamCity test review complete

#3345 Issue 45461: Levey-Jennings error bars vertical lines add visual noise
  internal/webapp/vis/src/geom.js
  internal/webapp/vis/src/internal/D3Renderer.js
  internal/webapp/vis/src/plot.js
Labels: TeamCity test review complete

#3343 Item 10353: Convert EditableGridPanelForUpdate to QueryModel based EditableGridPanel
  core/package-lock.json
  core/package.json
Labels: TeamCity test review complete

#3351 Issue 45091: Adjust savePolicy() to not expect a SecurityPolicy
  core/package-lock.json
  core/package.json
Labels: TeamCity test review complete

#3334 Limit active users
  api/src/org/labkey/api/admin/AdminBean.java
  api/src/org/labkey/api/cache/CacheManager.java
  api/src/org/labkey/api/collections/LabKeyCollectors.java
  api/src/org/labkey/api/module/ModuleLoader.java
  api/src/org/labkey/api/security/LimitActiveUsersService.java
  api/src/org/labkey/api/security/SecurityManager.java
  api/src/org/labkey/api/security/User.java
  api/src/org/labkey/api/security/UserCache.java
  api/src/org/labkey/api/security/UserManager.java
  api/src/org/labkey/api/settings/AbstractSettingsGroup.java
  api/src/org/labkey/api/settings/AbstractWriteableSettingsGroup.java
  api/src/org/labkey/api/settings/WriteableAppProps.java
  core/module.properties
  core/package-lock.json
  core/package.json
  core/resources/schemas/core.xml
  core/resources/schemas/dbscripts/postgresql/core-22.001-22.002.sql
  core/resources/schemas/dbscripts/postgresql/core-create.sql
  core/resources/schemas/dbscripts/sqlserver/core-22.001-22.002.sql
  core/resources/schemas/test.xml
  core/src/client/LabKeyUIComponentsPage/UsersGridPanelPage.tsx
  core/src/org/labkey/core/CoreModule.java
  core/src/org/labkey/core/admin/admin.jsp
  core/src/org/labkey/core/admin/customizeSite.jsp
  core/src/org/labkey/core/login/LoginController.java
  core/src/org/labkey/core/query/UsersTable.java
  core/src/org/labkey/core/security/SecurityApiActions.java
  core/src/org/labkey/core/security/SecurityController.java
  core/src/org/labkey/core/security/addUsers.jsp
  core/src/org/labkey/core/security/group.jsp
  core/src/org/labkey/core/user/LimitActiveUsersSettings.java
  core/src/org/labkey/core/user/UserController.java
  core/src/org/labkey/core/user/limitActiveUsers.jsp
  core/src/org/labkey/core/user/toggleInactive.jsp
  core/src/org/labkey/core/view/template/bootstrap/CoreWarningProvider.java
  core/webapp/Security/util/SecurityCache.js
  core/webapp/Security/window/UserInfoPopup.js
  internal/src/org/labkey/api/security/AuthFilter.java
  specimen/src/org/labkey/specimen/SpecimenRequestManager.java
Labels: TeamCity test review complete

#3381 Item 10394: Updates for incorporating ELN in LKSM
  core/api-src/org/labkey/api/products/ProductMenuProvider.java
  core/api-src/org/labkey/api/products/ProductRegistry.java
Labels: issue verification complete, TeamCity test review complete

#3388 Issue 45534: Include full +/- 3 SD range for multi-series plots with SD as y-axis range
  internal/webapp/vis/src/plot.js
Labels: TeamCity test review complete
