Repository LabKey/platform, pull requests merged in 2022-03, with the labels that each got.

#3131 Close open stream that was causing IOExceptions
  api/src/org/labkey/api/assay/AbstractAssayTsvDataHandler.java
  api/src/org/labkey/api/assay/AssayFileWriter.java
  api/src/org/labkey/api/assay/TsvDataHandler.java
  api/src/org/labkey/api/data/ExcelColumn.java
  api/src/org/labkey/api/data/SqlScriptExecutor.java
  api/src/org/labkey/api/dataiterator/DataIteratorUtil.java
  api/src/org/labkey/api/query/AbstractQueryImportAction.java
  api/src/org/labkey/api/query/QueryImportPipelineJob.java
  api/src/org/labkey/api/reader/ExcelFactory.java
  api/src/org/labkey/api/reader/ExcelLoader.java
  api/src/org/labkey/api/reader/jxl/JxlWorkbook.java
  api/src/org/labkey/api/util/FileUtil.java
  assay/api-src/org/labkey/api/assay/plate/ExcelPlateReader.java
  assay/api-src/org/labkey/api/assay/plate/PlateSampleFilePropertyHelper.java
  assay/src/org/labkey/assay/pipeline/AssayImportRunTask.java
  experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
  internal/src/org/labkey/api/exp/property/DomainTemplate.java
  specimen/src/org/labkey/specimen/pipeline/SampleMindedTransformTask.java
  study/test/src/org/labkey/test/tests/study/ProgressReportTest.java
Labels: needs TeamCity test review

#3144 Issue 45042: Domain creation and save APIs don't properly set the description value for the domain
  experiment/src/org/labkey/experiment/api/DataClassDomainKind.java
  list/src/org/labkey/list/model/ListDomainKind.java
  study/src/org/labkey/study/model/DatasetDomainKind.java
Labels: TeamCity test review complete

#3183 Issue 45132: Semicolon in file name truncates only on download
  core/src/org/labkey/core/webdav/DavController.java
Labels: needs issue verification, needs TeamCity test review

#3182 Issue 45122: Default filesystem couldn't parse S3 based URI
  pipeline/src/org/labkey/pipeline/status/StatusDetailsBean.java
Labels: needs TeamCity test review

#3179 Item 10191: App grid column header filter and sort menu options and usage of filter modal (experimental feature)
  core/package-lock.json
  core/package.json
  core/src/client/LabKeyUIComponentsPage/EditableGridPage.tsx
Labels: issue verification complete, TeamCity test review complete
