Repository LabKey/platform, pull requests merged in 2022-04, with the labels that each got.

#3194 Issue 45154: Project Creator can't create from template
  api/src/org/labkey/api/data/ContainerManager.java
  core/src/org/labkey/core/admin/AdminController.java
Labels: issue verification complete, needs issue verification

#3218 Remove QueryGridPanel and related components and action/util functions
  core/package-lock.json
  core/package.json
  core/src/client/LabKeyUIComponentsPage/SchemaQueryInputProvider.tsx
Labels: TeamCity test review complete

#3219 Item 10223: App GridPanel update to display filter/search pills in grid message area (experimental feature)
  core/package-lock.json
  core/package.json
Labels: issue verification complete, TeamCity test review complete

#3247 Item 10253: Remove experimental feature to officially switch to new Grid Filtering UX changes
  core/package-lock.json
  core/package.json
Labels: TeamCity test review complete

#3279 D3Renderer.js null check for plot.originalAes
  internal/webapp/vis/src/internal/D3Renderer.js
Labels: TeamCity test review complete

#3291 Issue 45331: Create folder/project wizard combos to use tpl for option display
  core/src/org/labkey/core/admin/createFolder.jsp
  core/src/org/labkey/core/admin/setFolderPermissions.jsp
Labels: TeamCity test review complete

#3296 Item 10275: Grid panel updates to make button/menu bar display responsive to screen width
  core/package-lock.json
  core/package.json
Labels: TeamCity test review complete
