Repository LabKey/platform, pull requests merged in 2022-12, with the labels that each got.

#3885 Updates for form consistency in apps: textarea resize vertically only
  assay/package-lock.json
  assay/package.json
  core/package-lock.json
  core/package.json
  experiment/package-lock.json
  experiment/package.json
  pipeline/package-lock.json
  pipeline/package.json
Labels: TeamCity test review complete

#3899 Add time stamp to file watcher triggered log files
  api/src/org/labkey/api/pipeline/file/AbstractFileAnalysisJob.java
  api/src/org/labkey/api/pipeline/file/AbstractFileAnalysisProtocol.java
  pipeline/src/org/labkey/pipeline/analysis/FileAnalysisPipelineProvider.java
  pipeline/src/org/labkey/pipeline/api/PipelineServiceImpl.java
Labels: code review complete, needs issue verification, TeamCity test review complete

#3909 Updates for creation of @labkey/premium package
  assay/package-lock.json
  assay/package.json
  core/package-lock.json
  core/package.json
  experiment/package-lock.json
  experiment/package.json
  pipeline/package-lock.json
  pipeline/package.json
Labels: TeamCity test review complete

#3916 Adjust file watcher jobs adding a timestamp to log file names.
  api/src/org/labkey/api/pipeline/PipelineService.java
  api/src/org/labkey/api/pipeline/file/AbstractFileAnalysisJob.java
  api/src/org/labkey/api/pipeline/file/AbstractFileAnalysisProtocol.java
  pipeline/src/org/labkey/pipeline/api/PipelineServiceImpl.java
Labels: needs TeamCity test review

#3926 Updates for data class consistency - general changes
  assay/package-lock.json
  assay/package.json
  assay/src/client/AssayTypeSelect/AssayTypeSelect.scss
  assay/src/org/labkey/assay/query/AssayListTable.java
  core/package-lock.json
  core/package.json
  core/src/client/AuthenticationConfiguration/authenticationConfiguration.scss
  core/src/client/LabKeyUIComponentsPage/LabKeyUIComponentsPage.tsx
  core/src/client/LabKeyUIComponentsPage/NavigationBarPage.tsx
  core/src/client/components/AuthConfigMasterPanel.tsx
  core/src/client/components/GlobalSettings.tsx
  core/src/client/components/__snapshots__/AuthConfigMasterPanel.spec.tsx.snap
  experiment/package-lock.json
  experiment/package.json
  pipeline/package-lock.json
  pipeline/package.json
Labels: TeamCity test review complete

#3964 Issue 47000: Re-importing standard assay with transform script fails because of reRunId on post URL
  api/src/org/labkey/api/assay/actions/UploadWizardAction.java
Labels: TeamCity test review complete
