Repository LabKey/platform, pull requests merged in 2023-10, with the labels that each got.

#4807 Misc assay related fixes for 23.11
  api/src/org/labkey/api/assay/AbstractAssayProvider.java
  assay/package-lock.json
  assay/package.json
  assay/src/org/labkey/assay/query/AssayListTable.java
  assay/src/org/labkey/assay/query/AssaySchemaImpl.java
  core/package-lock.json
  core/package.json
  experiment/package-lock.json
  experiment/package.json
  pipeline/package-lock.json
  pipeline/package.json
Labels: TeamCity test review complete

#4839 Update list search timestamp to only update if resource not deleted
  list/src/org/labkey/list/model/ListManager.java
Labels: needs code review, needs TeamCity test review

#4843 LabKeyUIComponentsPage.tsx update to limit included @labkey/components
  core/src/client/LabKeyUIComponentsPage/AssayImportPage.tsx
  core/src/client/LabKeyUIComponentsPage/DetailPage.tsx
  core/src/client/LabKeyUIComponentsPage/GridPanelPage.tsx
  core/src/client/LabKeyUIComponentsPage/LabKeyUIComponentsPage.tsx
  core/src/client/LabKeyUIComponentsPage/LineagePage.tsx
  core/src/client/LabKeyUIComponentsPage/QueriesListingPage.tsx
  core/src/client/LabKeyUIComponentsPage/SchemaQueryInputProvider.tsx
  core/src/client/LabKeyUIComponentsPage/UserProfilePage.tsx
  core/src/client/LabKeyUIComponentsPage/UsersGridPanelPage.tsx
  core/src/client/LabKeyUIComponentsPage/constants.ts
Labels: TeamCity test review complete

#4882 ToggleButton updates per UX review
  core/package-lock.json
  core/package.json
  core/src/client/components/DynamicConfigurationModal.tsx
  core/src/client/components/__snapshots__/DynamicConfigurationModal.spec.tsx.snap
Labels: TeamCity test review complete

#4879 Issue 41677: Include single field uniqueness constraint option in field editor
  api/gwtsrc/org/labkey/api/gwt/client/model/GWTDomain.java
  api/src/org/labkey/api/exp/api/SampleTypeDomainKind.java
  api/src/org/labkey/api/exp/property/Domain.java
  api/src/org/labkey/api/exp/property/DomainKind.java
  api/src/org/labkey/api/exp/property/DomainUtil.java
  api/src/org/labkey/api/issues/AbstractIssuesListDefDomainKind.java
  assay/src/org/labkey/assay/PlateBasedAssaySampleTypeDomainKind.java
  bigiron/src/org/labkey/bigiron/mssql/BaseMicrosoftSqlServerDialect.java
  core/package-lock.json
  core/package.json
  experiment/src/org/labkey/experiment/api/DataClassDomainKind.java
  experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
  experiment/src/org/labkey/experiment/api/SampleTypeServiceImpl.java
  experiment/src/org/labkey/experiment/api/property/DomainImpl.java
  list/src/org/labkey/list/model/ListDomainKind.java
  study/api-src/org/labkey/api/specimen/SpecimenSampleTypeDomainKind.java
  study/src/org/labkey/study/model/DatasetDomainKind.java
  study/test/src/org/labkey/test/tests/study/StudyDatasetIndexTest.java
Labels: issue verification complete, TeamCity test review complete
