Repository LabKey/platform, pull requests merged in 2024-05, with the labels that each got.

#5480 Issue 50212: ScriptsResourceProvider.resolve to catch AccessDeniedException for @scripts dir
  experiment/src/org/labkey/experiment/ScriptsResourceProvider.java
Labels: TeamCity test review complete

#5471 Issue 50299: Sample Type grid "Edit in Bulk" doesn't always save files to the file system
  experiment/src/org/labkey/experiment/ExpDataIterators.java
Labels: issue verification complete, TeamCity test review complete

#5504 Chart builder in app (part 2)
  visualization/resources/web/vis/genericChart/genericChartHelper.js
Labels: TeamCity test review complete

#5509 Increase timeout for TikaTestCase
  api/src/org/labkey/api/test/TestTimeout.java
  search/src/org/labkey/search/model/LuceneSearchServiceImpl.java
Labels: Review effort [1-5]: 2
