Repository LabKey/platform, pull requests merged in 2024-08, with the labels that each got.

#5735 Issue 50926: Authentication Configuration on Small Screen
  core/src/client/AuthenticationConfiguration/authenticationConfiguration.scss
Labels: needs TeamCity test review

#5777 Calculated fields validation of expression in Field Editor
  api/src/org/labkey/api/assay/AssayProtocolSchema.java
  assay/package-lock.json
  assay/package.json
  core/package-lock.json
  core/package.json
  experiment/package-lock.json
  experiment/package.json
  pipeline/package-lock.json
  pipeline/package.json
  query/src/org/labkey/query/MetadataTableJSON.java
  query/src/org/labkey/query/persist/QueryManager.java
  query/webapp/query/browser/view/QueryDetails.js
  study/src/org/labkey/study/query/AssayDatasetTable.java
Labels: issue verification complete, TeamCity test review complete

#5788 Issue 50822: Query to get study properties instead of relying on study moduleContext
  core/package-lock.json
  core/package.json
Labels: TeamCity test review complete

#5793 Issue 51021: Remove websocket check for Abnormal Closure event and rely on checkForExpiredSession() instead
  api/webapp/clientapi/dom/WebSocket.js
Labels: TeamCity test review complete

#5796 Consolidate EditableGrid read-only cell methods
  assay/package-lock.json
  assay/package.json
  core/package-lock.json
  core/package.json
  experiment/package-lock.json
  experiment/package.json
  pipeline/package-lock.json
  pipeline/package.json
Labels: issue verification complete, TeamCity test review complete
