Repository LabKey/platform, pull requests merged in 2024-10, with the labels that each got.

#5907 attempt to fix intermittently-failing test in StudySimpleExportTest
  study/test/src/org/labkey/test/tests/study/StudySimpleExportTest.java
Labels: needs code review

#5897 LIMS: Charting Story #3 - audit logs, cross folder & rendering improvements
  api/src/org/labkey/api/reports/report/ReportDescriptor.java
  api/src/org/labkey/api/reports/report/view/ReportDesignBean.java
  api/src/org/labkey/api/reports/report/view/ReportUtil.java
  assay/package-lock.json
  assay/package.json
  core/package-lock.json
  core/package.json
  core/webapp/vis/src/internal/D3Renderer.js
  experiment/package-lock.json
  experiment/package.json
  pipeline/package-lock.json
  pipeline/package.json
  query/src/org/labkey/query/QueryModule.java
  query/src/org/labkey/query/reports/ReportAuditProvider.java
  query/src/org/labkey/query/reports/ReportServiceImpl.java
  visualization/resources/web/vis/chartWizard/baseChartWizardPanel.js
  visualization/resources/web/vis/chartWizard/genericChartPanel.js
  visualization/resources/web/vis/chartWizard/saveOptionsPanel.js
  visualization/resources/web/vis/genericChart/genericChartHelper.js
  visualization/src/org/labkey/visualization/VisualizationController.java
  visualization/src/org/labkey/visualization/views/chartWizard.jsp
Labels: issue verification complete, TeamCity test review complete

#5924 Misc 24.11 fixes
  api/src/org/labkey/api/exp/api/ExperimentService.java
  api/src/org/labkey/api/security/roles/AuthorRole.java
  core/src/client/components/__snapshots__/DynamicConfigurationModal.spec.tsx.snap
  experiment/src/org/labkey/experiment/api/ExpDataClassDataTestCase.jsp
  experiment/src/org/labkey/experiment/api/ExpSampleTypeTestCase.jsp
  experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
  experiment/src/org/labkey/experiment/api/SampleTypeServiceImpl.java
  experiment/src/org/labkey/experiment/samples/DataClassFolderWriter.java
  experiment/src/org/labkey/experiment/xar/XarExportSelection.java
Labels: TeamCity test review complete

#5935 PlateGridInfo parsing to support measure annotations only when plate set only has a single plate
  api/src/org/labkey/api/exp/property/PropertyService.java
  assay/src/org/labkey/assay/plate/AssayPlateMetadataServiceImpl.java
  experiment/src/org/labkey/experiment/api/property/PropertyServiceImpl.java
Labels: TeamCity test review complete

#5969 Misc 24.11 Fixes
  api/src/org/labkey/api/data/AbstractTableInfo.java
  assay/src/org/labkey/assay/AssayDomainServiceImpl.java
  core/src/org/labkey/core/view/configReportsAndScripts.jsp
  core/webapp/internal/ViewDesigner/tab/ColumnsTab.js
Labels: TeamCity test review complete
