Repository LabKey/platform, pull requests merged in 2024-07, with the labels that each got.

#5642 Misc 24.8 fixes and test cases
  experiment/src/org/labkey/experiment/api/ExpMaterialImpl.java
  experiment/src/org/labkey/experiment/api/ExpRunTableImpl.java
Labels: TeamCity test review complete

#5676 Issue 49830: Update inferColumnInfo to force fields of type File to use ExpDataFileConverter
  api/src/org/labkey/api/reader/DataLoader.java
Labels: TeamCity test review complete

#5677 Support for calculated fields in Field Editor UI for certain data types
  api/gwtsrc/org/labkey/api/gwt/client/model/GWTDomain.java
  api/gwtsrc/org/labkey/api/gwt/client/model/GWTPropertyDescriptor.java
  api/gwtsrc/org/labkey/api/gwt/client/ui/PropertyType.java
  api/src/org/labkey/api/data/AbstractTableInfo.java
  api/src/org/labkey/api/data/ColumnInfo.java
  api/src/org/labkey/api/data/JsonWriter.java
  api/src/org/labkey/api/exp/api/SampleTypeDomainKind.java
  api/src/org/labkey/api/exp/property/DomainKind.java
  api/src/org/labkey/api/exp/property/DomainUtil.java
  api/src/org/labkey/api/query/MetadataColumnJSON.java
  api/src/org/labkey/api/query/MetadataUnavailableException.java
  api/src/org/labkey/api/query/QueryService.java
  api/src/org/labkey/api/settings/ProductFeature.java
  api/src/org/labkey/api/view/DataView.java
  assay/api-src/org/labkey/api/assay/AssayBatchDomainKind.java
  assay/api-src/org/labkey/api/assay/AssayResultDomainKind.java
  assay/api-src/org/labkey/api/assay/AssayResultTable.java
  assay/api-src/org/labkey/api/assay/AssayRunDomainKind.java
  assay/package-lock.json
  assay/package.json
  assay/src/org/labkey/assay/AssayDomainServiceImpl.java
  assay/src/org/labkey/assay/AssayIntegrationTestCase.jsp
  assay/src/org/labkey/assay/PlateBasedAssaySampleTypeDomainKind.java
  assay/src/org/labkey/assay/data/generator/AssayDesignGenerator.java
  core/package-lock.json
  core/package.json
  core/src/org/labkey/core/CoreModule.java
  experiment/package-lock.json
  experiment/package.json
  experiment/src/org/labkey/experiment/CustomProperties.jsp
  experiment/src/org/labkey/experiment/CustomPropertiesView.java
  experiment/src/org/labkey/experiment/api/DataClassDomainKind.java
  experiment/src/org/labkey/experiment/api/ExpDataClassDataTableImpl.java
  experiment/src/org/labkey/experiment/api/ExpMaterialTableImpl.java
  experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
  experiment/src/org/labkey/experiment/api/SampleTypeServiceImpl.java
  experiment/src/org/labkey/experiment/api/property/GWTDomainMixin.java
  experiment/src/org/labkey/experiment/controllers/exp/ExperimentController.java
  list/src/org/labkey/list/model/ListDomainKind.java
  list/src/org/labkey/list/model/ListTable.java
  pipeline/package-lock.json
  pipeline/package.json
  query/src/org/labkey/query/AutoGeneratedDetailsCustomView.java
  query/src/org/labkey/query/MetadataTableJSON.java
  query/src/org/labkey/query/QueryServiceImpl.java
  query/src/org/labkey/query/controllers/QueryController.java
  query/src/org/labkey/query/sql/CalculatedExpressionColumn.java
  study/api-src/org/labkey/api/specimen/SpecimenSampleTypeDomainKind.java
  study/src/org/labkey/study/model/DatasetDomainKind.java
  study/src/org/labkey/study/query/DatasetTableImpl.java
  study/src/org/labkey/study/view/typeSummary.jsp
Labels: issue verification complete, TeamCity test review complete

#5706 Misc 24.8 fixes (issues 49753, 49754, 50537, 50449)
  core/package-lock.json
  core/package.json
  core/webapp/vis/MeasureStore.js
  core/webapp/vis/src/utils.js
  visualization/resources/web/vis/chartWizard/genericChartPanel.js
  visualization/resources/web/vis/genericChart/genericChartHelper.js
Labels: issue verification complete, TeamCity test review complete

#5713 Stream runs from the ExpRuns table
  api/src/org/labkey/api/exp/api/ExperimentService.java
  assay/src/org/labkey/assay/AssayManager.java
  experiment/src/org/labkey/experiment/api/ExperimentServiceImpl.java
  experiment/src/org/labkey/experiment/xar/FolderXarWriterFactory.java
Labels: needs issue verification, needs manual testing
